//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// @ 8..16  length       double       8B  (Rectangle)
/// @16..24  width        double       8B  (Rectangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle       8B
/// Rectangle   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
public readonly partial struct Shape : global::System.IEquatable<Shape>
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
        Rectangle = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_length;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_width;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Rectangle(double length, double width)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Rectangle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_length) = length;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_width) = width;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;
    public bool IsRectangle => _tag == Tags.Rectangle;

    public double CircleRadius
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }
    public double RectangleLength
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_length;
        }
    }
    public double RectangleWidth
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_width;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == Tags.Circle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public bool TryGetRectangle(out double length, out double width)
    {
        if (_tag == Tags.Rectangle)
        {
            length = _rectangle_length;
            width = _rectangle_width;
            return true;
        }

        length = default!;
        width = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, double, TResult> rectangle)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_radius),
            Tags.Rectangle => rectangle(_rectangle_length, _rectangle_width),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double, double> rectangle)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_radius); break;
            case Tags.Rectangle: rectangle(_rectangle_length, _rectangle_width); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Shape(double value) => Circle(value);

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Circle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_circle_radius, other._circle_radius),
            Tags.Rectangle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rectangle_length, other._rectangle_length) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rectangle_width, other._rectangle_width),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Circle => global::System.HashCode.Combine(_tag, _circle_radius),
            Tags.Rectangle => global::System.HashCode.Combine(_tag, _rectangle_length, _rectangle_width),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_radius})",
            Tags.Rectangle => $"Rectangle({_rectangle_length}, {_rectangle_width})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
