//HintName: Option.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>8 bytes</b> · align 4 · 3B padding</para>
/// <code>
/// @0..1  _tag         byte         1B
/// @1..4  ---          padding      3B
/// @4..8  value        int          4B  (Some)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Some    4B
/// None    0B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 8)]
public readonly partial struct Option : global::System.IEquatable<Option>
{
    public enum Tags : byte
    {
        Default = 0,
        Some = 1,
        None = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _some_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Option() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Option Some(int value)
    {
        var result = default(Option);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Some;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._some_value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Option None()
    {
        var result = default(Option);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.None;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsSome => _tag == Tags.Some;
    public bool IsNone => _tag == Tags.None;

    public int SomeValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Some) ThrowInvalidCase(nameof(Some));
            return _some_value;
        }
    }

    public bool TryGetSome(out int value)
    {
        if (_tag == Tags.Some)
        {
            value = _some_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetNone() => _tag == Tags.None;

    public TResult Match<TResult>(global::System.Func<int, TResult> some, global::System.Func<TResult> none)
    {
        return _tag switch
        {
            Tags.Some => some(_some_value),
            Tags.None => none(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int> some, global::System.Action none)
    {
        switch (_tag)
        {
            case Tags.Some: some(_some_value); break;
            case Tags.None: none(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Option(int value) => Some(value);

    public bool Equals(Option other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Some => _some_value == other._some_value,
            Tags.None => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Option other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Some => global::System.HashCode.Combine(_tag, _some_value),
            Tags.None => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Option left, Option right) => left.Equals(right);
    public static bool operator !=(Option left, Option right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Some => $"Some({_some_value})",
            Tags.None => "None",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
