//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// @ 8..16  length       double       8B  (Rectangle)
/// @16..24  width        double       8B  (Rectangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle       8B
/// Rectangle   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
public readonly partial struct Shape : global::System.IEquatable<Shape>
{
    private const byte TagCircle = 1;
    private const byte TagRectangle = 2;

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly byte _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _circle_radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _rectangle_length;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    private readonly double _rectangle_width;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    public static partial Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagCircle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    public static partial Shape Rectangle(double length, double width)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagRectangle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_length) = length;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_width) = width;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsCircle => _tag == TagCircle;
    public bool IsRectangle => _tag == TagRectangle;

    public double CircleRadius
    {
        get
        {
            if (_tag != TagCircle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }
    public double RectangleLength
    {
        get
        {
            if (_tag != TagRectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_length;
        }
    }
    public double RectangleWidth
    {
        get
        {
            if (_tag != TagRectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_width;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == TagCircle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public bool TryGetRectangle(out double length, out double width)
    {
        if (_tag == TagRectangle)
        {
            length = _rectangle_length;
            width = _rectangle_width;
            return true;
        }

        length = default!;
        width = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, double, TResult> rectangle)
    {
        return _tag switch
        {
            TagCircle => circle(_circle_radius),
            TagRectangle => rectangle(_rectangle_length, _rectangle_width),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double, double> rectangle)
    {
        switch (_tag)
        {
            case TagCircle: circle(_circle_radius); break;
            case TagRectangle: rectangle(_rectangle_length, _rectangle_width); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagCircle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_circle_radius, other._circle_radius),
            TagRectangle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rectangle_length, other._rectangle_length) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rectangle_width, other._rectangle_width),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagCircle => global::System.HashCode.Combine(_tag, _circle_radius),
            TagRectangle => global::System.HashCode.Combine(_tag, _rectangle_length, _rectangle_width),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagCircle => $"Circle({_circle_radius})",
            TagRectangle => $"Rectangle({_rectangle_length}, {_rectangle_width})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
