//HintName: Wrapper.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 1 variant.
/// </summary>
/// <remarks>
/// <para><b>8 bytes</b> · align 4 · 3B padding</para>
/// <code>
/// @0..1  _tag         byte         1B
/// @1..4  ---          padding      3B
/// @4..8  x            int          4B  (Value)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Value    4B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 8)]
public readonly partial struct Wrapper : global::System.IEquatable<Wrapper>
{
    public enum Tags : byte
    {
        Default = 0,
        Value = 1,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _value_x;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Wrapper() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Wrapper Value(int x)
    {
        var result = default(Wrapper);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Value;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._value_x) = x;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsValue => _tag == Tags.Value;

    public int ValueX
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Value) ThrowInvalidCase(nameof(Value));
            return _value_x;
        }
    }

    public bool TryGetValue(out int x)
    {
        if (_tag == Tags.Value)
        {
            x = _value_x;
            return true;
        }

        x = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<int, TResult> value)
    {
        return _tag switch
        {
            Tags.Value => value(_value_x),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, int, TResult> value)
    {
        return _tag switch
        {
            Tags.Value => value(state, _value_x),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int> value)
    {
        switch (_tag)
        {
            case Tags.Value: value(_value_x); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, int> value)
    {
        switch (_tag)
        {
            case Tags.Value: value(state, _value_x); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Wrapper(int value) => Value(value);

    public bool Equals(Wrapper other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Value => _value_x == other._value_x,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Wrapper other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Value => global::System.HashCode.Combine(_tag, _value_x),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Wrapper left, Wrapper right) => left.Equals(right);
    public static bool operator !=(Wrapper left, Wrapper right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Value => $"Value({_value_x})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
