//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 1 variant.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  base         double       8B  (Triangle)
/// @16..24  height       double       8B  (Triangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Triangle   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
public readonly partial struct Shape : global::System.IEquatable<Shape>
{
    public enum Tags : byte
    {
        Default = 0,
        Triangle = 1,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _triangle_base;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _triangle_height;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    public static partial Shape Triangle(double @base, double height)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Triangle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._triangle_base) = @base;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._triangle_height) = height;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsTriangle => _tag == Tags.Triangle;

    public double TriangleBase
    {
        get
        {
            if (_tag != Tags.Triangle) ThrowInvalidCase(nameof(Triangle));
            return _triangle_base;
        }
    }
    public double TriangleHeight
    {
        get
        {
            if (_tag != Tags.Triangle) ThrowInvalidCase(nameof(Triangle));
            return _triangle_height;
        }
    }

    public bool TryGetTriangle(out double @base, out double height)
    {
        if (_tag == Tags.Triangle)
        {
            @base = _triangle_base;
            height = _triangle_height;
            return true;
        }

        @base = default!;
        height = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, double, TResult> triangle)
    {
        return _tag switch
        {
            Tags.Triangle => triangle(_triangle_base, _triangle_height),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double, double> triangle)
    {
        switch (_tag)
        {
            case Tags.Triangle: triangle(_triangle_base, _triangle_height); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Triangle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_triangle_base, other._triangle_base) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_triangle_height, other._triangle_height),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Triangle => global::System.HashCode.Combine(_tag, _triangle_base, _triangle_height),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Triangle => $"Triangle({_triangle_base}, {_triangle_height})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
