//HintName: MyShape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  Radius       double       8B  (Circle)
/// @ 8..16  Side         double       8B  (Square)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle    8B
/// Square    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct MyShape : global::System.IEquatable<MyShape>
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
        Square = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_Radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _square_Side;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public MyShape() { }

    public static MyShape Circle(double radius)
    {
        var result = default(MyShape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_Radius) = radius;
        return result;
    }

    public static MyShape Square(double side)
    {
        var result = default(MyShape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Square;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._square_Side) = side;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;
    public bool IsSquare => _tag == Tags.Square;

    public double CircleRadius
    {
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_Radius;
        }
    }
    public double SquareSide
    {
        get
        {
            if (_tag != Tags.Square) ThrowInvalidCase(nameof(Square));
            return _square_Side;
        }
    }

    public bool TryGetCircle(out double Radius)
    {
        if (_tag == Tags.Circle)
        {
            Radius = _circle_Radius;
            return true;
        }

        Radius = default!;
        return false;
    }

    public bool TryGetSquare(out double Side)
    {
        if (_tag == Tags.Square)
        {
            Side = _square_Side;
            return true;
        }

        Side = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, TResult> square)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_Radius),
            Tags.Square => square(_square_Side),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double> square)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_Radius); break;
            case Tags.Square: square(_square_Side); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public bool Equals(MyShape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Circle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_circle_Radius, other._circle_Radius),
            Tags.Square => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_square_Side, other._square_Side),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is MyShape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Circle => global::System.HashCode.Combine(_tag, _circle_Radius),
            Tags.Square => global::System.HashCode.Combine(_tag, _square_Side),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(MyShape left, MyShape right) => left.Equals(right);
    public static bool operator !=(MyShape left, MyShape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_Radius})",
            Tags.Square => $"Square({_square_Side})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
