//HintName: MyShape.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  Radius       double       8B  (Circle)
/// @ 8..16  Side         double       8B  (Square)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle    8B
/// Square    8B
/// </code>
/// </remarks>
public partial class ShapeDef { }
