//HintName: Result.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Code         int          4B  (Error)
/// @ 4.. 8  Value        int          4B  (Ok)
/// @ 8..16  Message      string       8B  (Error)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Ok       4B
/// Error   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct Result : global::System.IEquatable<Result>
{
    public enum Tags : byte
    {
        Default = 0,
        Ok = 1,
        Error = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _ok_Value;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _error_Code;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly string _error_Message;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Result() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Result Ok(int value)
    {
        var result = default(Result);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Ok;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._ok_Value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Result Error(int code, string message)
    {
        var result = default(Result);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Error;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._error_Code) = code;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._error_Message) = message;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsOk => _tag == Tags.Ok;
    public bool IsError => _tag == Tags.Error;

    public int OkValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Ok) ThrowInvalidCase(nameof(Ok));
            return _ok_Value;
        }
    }
    public int ErrorCode
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Error) ThrowInvalidCase(nameof(Error));
            return _error_Code;
        }
    }
    public string ErrorMessage
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Error) ThrowInvalidCase(nameof(Error));
            return _error_Message;
        }
    }

    public bool TryGetOk(out int Value)
    {
        if (_tag == Tags.Ok)
        {
            Value = _ok_Value;
            return true;
        }

        Value = default!;
        return false;
    }

    public bool TryGetError(out int Code, out string Message)
    {
        if (_tag == Tags.Error)
        {
            Code = _error_Code;
            Message = _error_Message;
            return true;
        }

        Code = default!;
        Message = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<int, TResult> ok, global::System.Func<int, string, TResult> error)
    {
        return _tag switch
        {
            Tags.Ok => ok(_ok_Value),
            Tags.Error => error(_error_Code, _error_Message),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, int, TResult> ok, global::System.Func<TState, int, string, TResult> error)
    {
        return _tag switch
        {
            Tags.Ok => ok(state, _ok_Value),
            Tags.Error => error(state, _error_Code, _error_Message),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int> ok, global::System.Action<int, string> error)
    {
        switch (_tag)
        {
            case Tags.Ok: ok(_ok_Value); break;
            case Tags.Error: error(_error_Code, _error_Message); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, int> ok, global::System.Action<TState, int, string> error)
    {
        switch (_tag)
        {
            case Tags.Ok: ok(state, _ok_Value); break;
            case Tags.Error: error(state, _error_Code, _error_Message); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Result(int value) => Ok(value);

    public bool Equals(Result other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Ok => _ok_Value == other._ok_Value,
            Tags.Error => _error_Code == other._error_Code && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_error_Message, other._error_Message),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Result other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Ok => global::System.HashCode.Combine(_tag, _ok_Value),
            Tags.Error => global::System.HashCode.Combine(_tag, _error_Code, _error_Message),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Result left, Result right) => left.Equals(right);
    public static bool operator !=(Result left, Result right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Ok => $"Ok({_ok_Value})",
            Tags.Error => $"Error({_error_Code}, {_error_Message})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
