//HintName: Shape.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Id           int          4B  (common)
/// @ 8..16  Radius       double       8B  (Circle)
/// @ 8..16  Length       double       8B  (Rectangle)
/// @16..24  Width        double       8B  (Rectangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle       8B
/// Rectangle   16B
/// </code>
/// </remarks>
public partial record ShapeRecord { }
