//HintName: Result.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Code         int          4B  (Error)
/// @ 4.. 8  Value        int          4B  (Ok)
/// @ 8..16  Message      string       8B  (Error)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Ok       4B
/// Error   16B
/// </code>
/// </remarks>
public partial class ResultRecord { }
