//HintName: Resource.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  value        int          4B  (Inline)
/// @ 8..16  owner        IMemoryOwner&lt;byte&gt;   8B  (Buffer)
/// @ 8..16  stream       MemoryStream   8B  (File)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// File      8B
/// Buffer    8B
/// Inline    4B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct Resource : global::System.IEquatable<Resource>, global::System.IDisposable, global::System.IAsyncDisposable
{
    public enum Tags : byte
    {
        Default = 0,
        File = 1,
        Buffer = 2,
        Inline = 3,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.IO.MemoryStream _file_stream;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.Buffers.IMemoryOwner<byte> _buffer_owner;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _inline_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Resource() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource File(global::System.IO.MemoryStream stream)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.File;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._file_stream) = stream;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource Buffer(global::System.Buffers.IMemoryOwner<byte> owner)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Buffer;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._buffer_owner) = owner;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource Inline(int value)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Inline;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._inline_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsFile => _tag == Tags.File;
    public bool IsBuffer => _tag == Tags.Buffer;
    public bool IsInline => _tag == Tags.Inline;

    public global::System.IO.MemoryStream FileStream
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.File) ThrowInvalidCase(nameof(File));
            return _file_stream;
        }
    }
    public global::System.Buffers.IMemoryOwner<byte> BufferOwner
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Buffer) ThrowInvalidCase(nameof(Buffer));
            return _buffer_owner;
        }
    }
    public int InlineValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Inline) ThrowInvalidCase(nameof(Inline));
            return _inline_value;
        }
    }

    public bool TryGetFile(out global::System.IO.MemoryStream stream)
    {
        if (_tag == Tags.File)
        {
            stream = _file_stream;
            return true;
        }

        stream = default!;
        return false;
    }

    public bool TryGetBuffer(out global::System.Buffers.IMemoryOwner<byte> owner)
    {
        if (_tag == Tags.Buffer)
        {
            owner = _buffer_owner;
            return true;
        }

        owner = default!;
        return false;
    }

    public bool TryGetInline(out int value)
    {
        if (_tag == Tags.Inline)
        {
            value = _inline_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::System.IO.MemoryStream, TResult> file, global::System.Func<global::System.Buffers.IMemoryOwner<byte>, TResult> buffer, global::System.Func<int, TResult> inline)
    {
        return _tag switch
        {
            Tags.File => file(_file_stream),
            Tags.Buffer => buffer(_buffer_owner),
            Tags.Inline => inline(_inline_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.IO.MemoryStream, TResult> file, global::System.Func<TState, global::System.Buffers.IMemoryOwner<byte>, TResult> buffer, global::System.Func<TState, int, TResult> inline)
    {
        return _tag switch
        {
            Tags.File => file(state, _file_stream),
            Tags.Buffer => buffer(state, _buffer_owner),
            Tags.Inline => inline(state, _inline_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.IO.MemoryStream> file, global::System.Action<global::System.Buffers.IMemoryOwner<byte>> buffer, global::System.Action<int> inline)
    {
        switch (_tag)
        {
            case Tags.File: file(_file_stream); break;
            case Tags.Buffer: buffer(_buffer_owner); break;
            case Tags.Inline: inline(_inline_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.IO.MemoryStream> file, global::System.Action<TState, global::System.Buffers.IMemoryOwner<byte>> buffer, global::System.Action<TState, int> inline)
    {
        switch (_tag)
        {
            case Tags.File: file(state, _file_stream); break;
            case Tags.Buffer: buffer(state, _buffer_owner); break;
            case Tags.Inline: inline(state, _inline_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Resource(global::System.IO.MemoryStream value) => File(value);
    public static implicit operator Resource(global::System.Buffers.IMemoryOwner<byte> value) => Buffer(value);
    public static implicit operator Resource(int value) => Inline(value);

    public bool Equals(Resource other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.File => global::System.Collections.Generic.EqualityComparer<global::System.IO.MemoryStream>.Default.Equals(_file_stream, other._file_stream),
            Tags.Buffer => global::System.Collections.Generic.EqualityComparer<global::System.Buffers.IMemoryOwner<byte>>.Default.Equals(_buffer_owner, other._buffer_owner),
            Tags.Inline => _inline_value == other._inline_value,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Resource other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.File => global::System.HashCode.Combine(_tag, _file_stream),
            Tags.Buffer => global::System.HashCode.Combine(_tag, _buffer_owner),
            Tags.Inline => global::System.HashCode.Combine(_tag, _inline_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Resource left, Resource right) => left.Equals(right);
    public static bool operator !=(Resource left, Resource right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.File => $"File({_file_stream})",
            Tags.Buffer => $"Buffer({_buffer_owner})",
            Tags.Inline => $"Inline({_inline_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    /// <summary>Disposes the active variant's IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public void Dispose()
    {
        switch (_tag)
        {
            case Tags.File:
                _file_stream?.Dispose();
                break;
            case Tags.Buffer:
                _buffer_owner?.Dispose();
                break;
        }
    }

    /// <summary>Asynchronously disposes the active variant's IAsyncDisposable / IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        switch (_tag)
        {
            case Tags.File:
                if (_file_stream is not null) await _file_stream.DisposeAsync().ConfigureAwait(false);
                break;
            case Tags.Buffer:
                _buffer_owner?.Dispose();
                break;
        }
    }

    /// <summary>Removes ownership of the File payload from <paramref name="self"/> and returns it. Sets <paramref name="self"/> to default so subsequent disposal is a no-op. Throws if the active variant is not File.</summary>
    public static global::System.IO.MemoryStream TakeFile(ref Resource self)
    {
        if (self._tag != Tags.File) ThrowInvalidCase(nameof(File));
        var value = self._file_stream;
        self = default;
        return value;
    }

    /// <summary>If the active variant is File, removes ownership of its payload, writes it to <paramref name="value"/>, sets <paramref name="self"/> to default, and returns true.</summary>
    public static bool TryTakeFile(ref Resource self, out global::System.IO.MemoryStream value)
    {
        if (self._tag == Tags.File)
        {
            value = self._file_stream;
            self = default;
            return true;
        }

        value = default!;
        return false;
    }

    /// <summary>Removes ownership of the Buffer payload from <paramref name="self"/> and returns it. Sets <paramref name="self"/> to default so subsequent disposal is a no-op. Throws if the active variant is not Buffer.</summary>
    public static global::System.Buffers.IMemoryOwner<byte> TakeBuffer(ref Resource self)
    {
        if (self._tag != Tags.Buffer) ThrowInvalidCase(nameof(Buffer));
        var value = self._buffer_owner;
        self = default;
        return value;
    }

    /// <summary>If the active variant is Buffer, removes ownership of its payload, writes it to <paramref name="value"/>, sets <paramref name="self"/> to default, and returns true.</summary>
    public static bool TryTakeBuffer(ref Resource self, out global::System.Buffers.IMemoryOwner<byte> value)
    {
        if (self._tag == Tags.Buffer)
        {
            value = self._buffer_owner;
            self = default;
            return true;
        }

        value = default!;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
