//HintName: Resource.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 1 variant.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  stream       FileStream   8B  (File)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// File    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct Resource : global::System.IEquatable<Resource>, global::System.IDisposable, global::System.IAsyncDisposable
{
    public enum Tags : byte
    {
        Default = 0,
        File = 1,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.IO.FileStream _file_stream;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Resource() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource File(global::System.IO.FileStream stream)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.File;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._file_stream) = stream;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsFile => _tag == Tags.File;

    public global::System.IO.FileStream FileStream
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.File) ThrowInvalidCase(nameof(File));
            return _file_stream;
        }
    }

    public bool TryGetFile(out global::System.IO.FileStream stream)
    {
        if (_tag == Tags.File)
        {
            stream = _file_stream;
            return true;
        }

        stream = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::System.IO.FileStream, TResult> file)
    {
        return _tag switch
        {
            Tags.File => file(_file_stream),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.IO.FileStream, TResult> file)
    {
        return _tag switch
        {
            Tags.File => file(state, _file_stream),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.IO.FileStream> file)
    {
        switch (_tag)
        {
            case Tags.File: file(_file_stream); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.IO.FileStream> file)
    {
        switch (_tag)
        {
            case Tags.File: file(state, _file_stream); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Resource(global::System.IO.FileStream value) => File(value);

    public bool Equals(Resource other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.File => global::System.Collections.Generic.EqualityComparer<global::System.IO.FileStream>.Default.Equals(_file_stream, other._file_stream),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Resource other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.File => global::System.HashCode.Combine(_tag, _file_stream),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Resource left, Resource right) => left.Equals(right);
    public static bool operator !=(Resource left, Resource right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.File => $"File({_file_stream})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    /// <summary>Disposes the active variant's IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public void Dispose()
    {
        switch (_tag)
        {
            case Tags.File:
                _file_stream?.Dispose();
                break;
        }
    }

    /// <summary>Asynchronously disposes the active variant's IAsyncDisposable / IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        switch (_tag)
        {
            case Tags.File:
                if (_file_stream is not null) await _file_stream.DisposeAsync().ConfigureAwait(false);
                break;
        }
    }

    /// <summary>Removes ownership of the File payload from <paramref name="self"/> and returns it. Sets <paramref name="self"/> to default so subsequent disposal is a no-op. Throws if the active variant is not File.</summary>
    public static global::System.IO.FileStream TakeFile(ref Resource self)
    {
        if (self._tag != Tags.File) ThrowInvalidCase(nameof(File));
        var value = self._file_stream;
        self = default;
        return value;
    }

    /// <summary>If the active variant is File, removes ownership of its payload, writes it to <paramref name="value"/>, sets <paramref name="self"/> to default, and returns true.</summary>
    public static bool TryTakeFile(ref Resource self, out global::System.IO.FileStream value)
    {
        if (self._tag == Tags.File)
        {
            value = self._file_stream;
            self = default;
            return true;
        }

        value = default!;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
