//HintName: Resource.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 1 variant.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  stream       MemoryStream   8B  (Tagged)
/// @16..24  label        string       8B  (Tagged)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Tagged   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
public readonly partial struct Resource : global::System.IEquatable<Resource>, global::System.IDisposable, global::System.IAsyncDisposable
{
    public enum Tags : byte
    {
        Default = 0,
        Tagged = 1,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.IO.MemoryStream _tagged_stream;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly string _tagged_label;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Resource() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource Tagged(global::System.IO.MemoryStream stream, string label)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Tagged;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tagged_stream) = stream;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tagged_label) = label;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsTagged => _tag == Tags.Tagged;

    public global::System.IO.MemoryStream TaggedStream
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Tagged) ThrowInvalidCase(nameof(Tagged));
            return _tagged_stream;
        }
    }
    public string TaggedLabel
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Tagged) ThrowInvalidCase(nameof(Tagged));
            return _tagged_label;
        }
    }

    public bool TryGetTagged(out global::System.IO.MemoryStream stream, out string label)
    {
        if (_tag == Tags.Tagged)
        {
            stream = _tagged_stream;
            label = _tagged_label;
            return true;
        }

        stream = default!;
        label = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::System.IO.MemoryStream, string, TResult> tagged)
    {
        return _tag switch
        {
            Tags.Tagged => tagged(_tagged_stream, _tagged_label),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.IO.MemoryStream, string, TResult> tagged)
    {
        return _tag switch
        {
            Tags.Tagged => tagged(state, _tagged_stream, _tagged_label),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.IO.MemoryStream, string> tagged)
    {
        switch (_tag)
        {
            case Tags.Tagged: tagged(_tagged_stream, _tagged_label); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.IO.MemoryStream, string> tagged)
    {
        switch (_tag)
        {
            case Tags.Tagged: tagged(state, _tagged_stream, _tagged_label); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public bool Equals(Resource other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Tagged => global::System.Collections.Generic.EqualityComparer<global::System.IO.MemoryStream>.Default.Equals(_tagged_stream, other._tagged_stream) && global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_tagged_label, other._tagged_label),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Resource other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Tagged => global::System.HashCode.Combine(_tag, _tagged_stream, _tagged_label),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Resource left, Resource right) => left.Equals(right);
    public static bool operator !=(Resource left, Resource right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Tagged => $"Tagged({_tagged_stream}, {_tagged_label})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    /// <summary>Disposes the active variant's IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public void Dispose()
    {
        switch (_tag)
        {
            case Tags.Tagged:
                _tagged_stream?.Dispose();
                break;
        }
    }

    /// <summary>Asynchronously disposes the active variant's IAsyncDisposable / IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        switch (_tag)
        {
            case Tags.Tagged:
                if (_tagged_stream is not null) await _tagged_stream.DisposeAsync().ConfigureAwait(false);
                break;
        }
    }

    /// <summary>Removes ownership of the Tagged payload from <paramref name="self"/> and writes its fields to the out parameters. Sets <paramref name="self"/> to default so subsequent disposal is a no-op. Throws if the active variant is not Tagged.</summary>
    public static void TakeTagged(ref Resource self, out global::System.IO.MemoryStream stream, out string label)
    {
        if (self._tag != Tags.Tagged) ThrowInvalidCase(nameof(Tagged));
        stream = self._tagged_stream;
        label = self._tagged_label;
        self = default;
    }

    /// <summary>If the active variant is Tagged, removes ownership of its payload, writes fields to the out parameters, sets <paramref name="self"/> to default, and returns true.</summary>
    public static bool TryTakeTagged(ref Resource self, out global::System.IO.MemoryStream stream, out string label)
    {
        if (self._tag == Tags.Tagged)
        {
            stream = self._tagged_stream;
            label = self._tagged_label;
            self = default;
            return true;
        }

        stream = default!;
        label = default!;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
