//HintName: Resource.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Value        int          4B  (Inline)
/// @ 8..16  Stream       MemoryStream   8B  (File)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// File      8B
/// Inline    4B
/// </code>
/// </remarks>
public partial record ResourceRecord { }
