//HintName: NumberUnion.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  value        double       8B  (Celsius)
/// @ 8..16  value        double       8B  (Fahrenheit)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Celsius       8B
/// Fahrenheit    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct NumberUnion : global::System.IEquatable<NumberUnion>
{
    public enum Tags : byte
    {
        Default = 0,
        Celsius = 1,
        Fahrenheit = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _celsius_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _fahrenheit_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public NumberUnion() { }

    public static partial NumberUnion Celsius(double value)
    {
        var result = default(NumberUnion);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Celsius;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._celsius_value) = value;
        return result;
    }

    public static partial NumberUnion Fahrenheit(double value)
    {
        var result = default(NumberUnion);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Fahrenheit;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._fahrenheit_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCelsius => _tag == Tags.Celsius;
    public bool IsFahrenheit => _tag == Tags.Fahrenheit;

    public double CelsiusValue
    {
        get
        {
            if (_tag != Tags.Celsius) ThrowInvalidCase(nameof(Celsius));
            return _celsius_value;
        }
    }
    public double FahrenheitValue
    {
        get
        {
            if (_tag != Tags.Fahrenheit) ThrowInvalidCase(nameof(Fahrenheit));
            return _fahrenheit_value;
        }
    }

    public bool TryGetCelsius(out double value)
    {
        if (_tag == Tags.Celsius)
        {
            value = _celsius_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetFahrenheit(out double value)
    {
        if (_tag == Tags.Fahrenheit)
        {
            value = _fahrenheit_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> celsius, global::System.Func<double, TResult> fahrenheit)
    {
        return _tag switch
        {
            Tags.Celsius => celsius(_celsius_value),
            Tags.Fahrenheit => fahrenheit(_fahrenheit_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> celsius, global::System.Action<double> fahrenheit)
    {
        switch (_tag)
        {
            case Tags.Celsius: celsius(_celsius_value); break;
            case Tags.Fahrenheit: fahrenheit(_fahrenheit_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public bool Equals(NumberUnion other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Celsius => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_celsius_value, other._celsius_value),
            Tags.Fahrenheit => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_fahrenheit_value, other._fahrenheit_value),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is NumberUnion other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Celsius => global::System.HashCode.Combine(_tag, _celsius_value),
            Tags.Fahrenheit => global::System.HashCode.Combine(_tag, _fahrenheit_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(NumberUnion left, NumberUnion right) => left.Equals(right);
    public static bool operator !=(NumberUnion left, NumberUnion right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Celsius => $"Celsius({_celsius_value})",
            Tags.Fahrenheit => $"Fahrenheit({_fahrenheit_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
