//HintName: Event.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  value        string       8B  (Tag)
/// @16..20  x            int          4B  (Click)
/// @20..24  y            int          4B  (Click)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Tag      8B
/// Click    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
public readonly partial struct Event : global::System.IEquatable<Event>
{
    public enum Tags : byte
    {
        Default = 0,
        Tag = 1,
        Click = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly string _tag_value;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _click_x;

    [global::System.Runtime.InteropServices.FieldOffset(20)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _click_y;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Event() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Event Tag(string value)
    {
        var result = default(Event);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Tag;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag_value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Event Click(int x, int y)
    {
        var result = default(Event);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Click;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._click_x) = x;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._click_y) = y;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Kind => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsTag => _tag == Tags.Tag;
    public bool IsClick => _tag == Tags.Click;

    public string TagValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Tag) ThrowInvalidCase(nameof(Tag));
            return _tag_value;
        }
    }
    public int ClickX
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Click) ThrowInvalidCase(nameof(Click));
            return _click_x;
        }
    }
    public int ClickY
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Click) ThrowInvalidCase(nameof(Click));
            return _click_y;
        }
    }

    public bool TryGetTag(out string value)
    {
        if (_tag == Tags.Tag)
        {
            value = _tag_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetClick(out int x, out int y)
    {
        if (_tag == Tags.Click)
        {
            x = _click_x;
            y = _click_y;
            return true;
        }

        x = default!;
        y = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<string, TResult> tag, global::System.Func<int, int, TResult> click)
    {
        return _tag switch
        {
            Tags.Tag => tag(_tag_value),
            Tags.Click => click(_click_x, _click_y),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<string> tag, global::System.Action<int, int> click)
    {
        switch (_tag)
        {
            case Tags.Tag: tag(_tag_value); break;
            case Tags.Click: click(_click_x, _click_y); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Event(string value) => Tag(value);

    public bool Equals(Event other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Tag => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_tag_value, other._tag_value),
            Tags.Click => _click_x == other._click_x && _click_y == other._click_y,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Event other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Tag => global::System.HashCode.Combine(_tag, _tag_value),
            Tags.Click => global::System.HashCode.Combine(_tag, _click_x, _click_y),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Event left, Event right) => left.Equals(right);
    public static bool operator !=(Event left, Event right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Tag => $"Tag({_tag_value})",
            Tags.Click => $"Click({_click_x}, {_click_y})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
