//HintName: DrawCmd.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  x            double       8B  (LineTo)
/// @ 8..16  x            double       8B  (MoveTo)
/// @16..24  y            double       8B  (LineTo)
/// @16..24  y            double       8B  (MoveTo)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// MoveTo   16B
/// LineTo   16B
/// Close     0B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
public readonly partial struct DrawCmd : global::System.IEquatable<DrawCmd>
{
    public enum Tags : byte
    {
        Default = 0,
        MoveTo = 1,
        LineTo = 2,
        Close = 3,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _moveto_x;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _moveto_y;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _lineto_x;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _lineto_y;

    public static class Cases
    {
        public readonly struct MoveTo
        {
            public double X { get; }
            public double Y { get; }

            public MoveTo(double x, double y)
            {
                X = x;
                Y = y;
            }
        }

        public readonly struct LineTo
        {
            public double X { get; }
            public double Y { get; }

            public LineTo(double x, double y)
            {
                X = x;
                Y = y;
            }
        }

    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public DrawCmd() { }

    public static partial DrawCmd MoveTo(double x, double y)
    {
        var result = default(DrawCmd);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.MoveTo;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._moveto_x) = x;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._moveto_y) = y;
        return result;
    }

    public static partial DrawCmd LineTo(double x, double y)
    {
        var result = default(DrawCmd);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.LineTo;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._lineto_x) = x;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._lineto_y) = y;
        return result;
    }

    public static partial DrawCmd Close()
    {
        var result = default(DrawCmd);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Close;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsMoveTo => _tag == Tags.MoveTo;
    public bool IsLineTo => _tag == Tags.LineTo;
    public bool IsClose => _tag == Tags.Close;

    public Cases.MoveTo AsMoveTo
    {
        get
        {
            if (_tag != Tags.MoveTo) ThrowInvalidCase(nameof(MoveTo));
            return new Cases.MoveTo(_moveto_x, _moveto_y);
        }
    }
    public Cases.LineTo AsLineTo
    {
        get
        {
            if (_tag != Tags.LineTo) ThrowInvalidCase(nameof(LineTo));
            return new Cases.LineTo(_lineto_x, _lineto_y);
        }
    }

    public bool TryGetMoveTo(out Cases.MoveTo data)
    {
        if (_tag == Tags.MoveTo)
        {
            data = new Cases.MoveTo(_moveto_x, _moveto_y);
            return true;
        }

        data = default;
        return false;
    }

    public bool TryGetLineTo(out Cases.LineTo data)
    {
        if (_tag == Tags.LineTo)
        {
            data = new Cases.LineTo(_lineto_x, _lineto_y);
            return true;
        }

        data = default;
        return false;
    }

    public bool TryGetClose() => _tag == Tags.Close;

    public TResult Match<TResult>(global::System.Func<double, double, TResult> moveTo, global::System.Func<double, double, TResult> lineTo, global::System.Func<TResult> close)
    {
        return _tag switch
        {
            Tags.MoveTo => moveTo(_moveto_x, _moveto_y),
            Tags.LineTo => lineTo(_lineto_x, _lineto_y),
            Tags.Close => close(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double, double> moveTo, global::System.Action<double, double> lineTo, global::System.Action close)
    {
        switch (_tag)
        {
            case Tags.MoveTo: moveTo(_moveto_x, _moveto_y); break;
            case Tags.LineTo: lineTo(_lineto_x, _lineto_y); break;
            case Tags.Close: close(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public bool Equals(DrawCmd other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.MoveTo => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_moveto_x, other._moveto_x) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_moveto_y, other._moveto_y),
            Tags.LineTo => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_lineto_x, other._lineto_x) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_lineto_y, other._lineto_y),
            Tags.Close => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is DrawCmd other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.MoveTo => global::System.HashCode.Combine(_tag, _moveto_x, _moveto_y),
            Tags.LineTo => global::System.HashCode.Combine(_tag, _lineto_x, _lineto_y),
            Tags.Close => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(DrawCmd left, DrawCmd right) => left.Equals(right);
    public static bool operator !=(DrawCmd left, DrawCmd right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.MoveTo => $"MoveTo({_moveto_x}, {_moveto_y})",
            Tags.LineTo => $"LineTo({_lineto_x}, {_lineto_y})",
            Tags.Close => "Close",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
