//HintName: Outer.Inner.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

partial class Outer<T>
{
    public readonly partial struct Inner : global::System.IEquatable<Inner>
    {
        public enum Tags : byte
        {
            Default = 0,
            A = 1,
            B = 2,
        }

        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly Tags _tag;
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly T _a_value;
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly int _b_count;

        [global::System.Obsolete("Use factory methods instead.", true)]
        public Inner() { }

        public static partial Inner A(T value)
        {
            var result = default(Inner);
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.A;
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._a_value) = value;
            return result;
        }

        public static partial Inner B(int count)
        {
            var result = default(Inner);
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.B;
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._b_count) = count;
            return result;
        }

        /// <summary>Gets the tag value identifying which variant is active.</summary>
        public Tags Tag => _tag;

        /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
        public bool IsDefault => _tag == Tags.Default;

        public bool IsA => _tag == Tags.A;
        public bool IsB => _tag == Tags.B;

        public T AValue
        {
            get
            {
                if (_tag != Tags.A) ThrowInvalidCase(nameof(A));
                return _a_value;
            }
        }
        public int BCount
        {
            get
            {
                if (_tag != Tags.B) ThrowInvalidCase(nameof(B));
                return _b_count;
            }
        }

        public bool TryGetA(out T value)
        {
            if (_tag == Tags.A)
            {
                value = _a_value;
                return true;
            }

            value = default!;
            return false;
        }

        public bool TryGetB(out int count)
        {
            if (_tag == Tags.B)
            {
                count = _b_count;
                return true;
            }

            count = default!;
            return false;
        }

        public TResult Match<TResult>(global::System.Func<T, TResult> a, global::System.Func<int, TResult> b)
        {
            return _tag switch
            {
                Tags.A => a(_a_value),
                Tags.B => b(_b_count),
                _ => ThrowUnknownTag<TResult>()
            };
        }

        public void Match(global::System.Action<T> a, global::System.Action<int> b)
        {
            switch (_tag)
            {
                case Tags.A: a(_a_value); break;
                case Tags.B: b(_b_count); break;
                default: ThrowUnknownTag(); break;
            }
        }

        public static implicit operator Inner(T value) => A(value);
        public static implicit operator Inner(int value) => B(value);

        public bool Equals(Inner other)
        {
            if (_tag != other._tag) return false;
            return _tag switch
            {
                Tags.A => global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(_a_value, other._a_value),
                Tags.B => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_b_count, other._b_count),
                _ => true
            };
        }

        public override bool Equals(object? obj) => obj is Inner other && Equals(other);

        public override int GetHashCode()
        {
            return _tag switch
            {
                Tags.A => global::System.HashCode.Combine(_tag, _a_value),
                Tags.B => global::System.HashCode.Combine(_tag, _b_count),
                _ => _tag.GetHashCode()
            };
        }

        public static bool operator ==(Inner left, Inner right) => left.Equals(right);
        public static bool operator !=(Inner left, Inner right) => !left.Equals(right);

        public override string ToString()
        {
            return _tag switch
            {
                Tags.A => $"A({_a_value})",
                Tags.B => $"B({_b_count})",
                Tags.Default => "Default",
                _ => "<invalid>"
            };
        }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static void ThrowInvalidCase(string caseName) =>
            throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static TResult ThrowUnknownTag<TResult>() =>
            throw new global::System.InvalidOperationException("Unknown union tag.");

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static void ThrowUnknownTag() =>
            throw new global::System.InvalidOperationException("Unknown union tag.");
    }
}
