//HintName: Mixed.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 4 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8.. 9  value        byte         1B  (ByteCase)
/// @ 8..12  value        float        4B  (FloatCase)
/// @ 8..12  value        int          4B  (IntCase)
/// @ 8..16  value        long         8B  (LongCase)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// IntCase      4B
/// LongCase     8B
/// ByteCase     1B
/// FloatCase    4B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
public readonly partial struct Mixed : global::System.IEquatable<Mixed>
{
    public enum Tags : byte
    {
        Default = 0,
        IntCase = 1,
        LongCase = 2,
        ByteCase = 3,
        FloatCase = 4,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly int _intcase_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly long _longcase_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly byte _bytecase_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly float _floatcase_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Mixed() { }

    public static partial Mixed IntCase(int value)
    {
        var result = default(Mixed);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.IntCase;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._intcase_value) = value;
        return result;
    }

    public static partial Mixed LongCase(long value)
    {
        var result = default(Mixed);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.LongCase;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._longcase_value) = value;
        return result;
    }

    public static partial Mixed ByteCase(byte value)
    {
        var result = default(Mixed);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.ByteCase;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._bytecase_value) = value;
        return result;
    }

    public static partial Mixed FloatCase(float value)
    {
        var result = default(Mixed);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.FloatCase;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._floatcase_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsIntCase => _tag == Tags.IntCase;
    public bool IsLongCase => _tag == Tags.LongCase;
    public bool IsByteCase => _tag == Tags.ByteCase;
    public bool IsFloatCase => _tag == Tags.FloatCase;

    public int IntCaseValue
    {
        get
        {
            if (_tag != Tags.IntCase) ThrowInvalidCase(nameof(IntCase));
            return _intcase_value;
        }
    }
    public long LongCaseValue
    {
        get
        {
            if (_tag != Tags.LongCase) ThrowInvalidCase(nameof(LongCase));
            return _longcase_value;
        }
    }
    public byte ByteCaseValue
    {
        get
        {
            if (_tag != Tags.ByteCase) ThrowInvalidCase(nameof(ByteCase));
            return _bytecase_value;
        }
    }
    public float FloatCaseValue
    {
        get
        {
            if (_tag != Tags.FloatCase) ThrowInvalidCase(nameof(FloatCase));
            return _floatcase_value;
        }
    }

    public bool TryGetIntCase(out int value)
    {
        if (_tag == Tags.IntCase)
        {
            value = _intcase_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetLongCase(out long value)
    {
        if (_tag == Tags.LongCase)
        {
            value = _longcase_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetByteCase(out byte value)
    {
        if (_tag == Tags.ByteCase)
        {
            value = _bytecase_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetFloatCase(out float value)
    {
        if (_tag == Tags.FloatCase)
        {
            value = _floatcase_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<int, TResult> intCase, global::System.Func<long, TResult> longCase, global::System.Func<byte, TResult> byteCase, global::System.Func<float, TResult> floatCase)
    {
        return _tag switch
        {
            Tags.IntCase => intCase(_intcase_value),
            Tags.LongCase => longCase(_longcase_value),
            Tags.ByteCase => byteCase(_bytecase_value),
            Tags.FloatCase => floatCase(_floatcase_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int> intCase, global::System.Action<long> longCase, global::System.Action<byte> byteCase, global::System.Action<float> floatCase)
    {
        switch (_tag)
        {
            case Tags.IntCase: intCase(_intcase_value); break;
            case Tags.LongCase: longCase(_longcase_value); break;
            case Tags.ByteCase: byteCase(_bytecase_value); break;
            case Tags.FloatCase: floatCase(_floatcase_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Mixed(int value) => IntCase(value);
    public static implicit operator Mixed(long value) => LongCase(value);
    public static implicit operator Mixed(byte value) => ByteCase(value);
    public static implicit operator Mixed(float value) => FloatCase(value);

    public bool Equals(Mixed other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.IntCase => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_intcase_value, other._intcase_value),
            Tags.LongCase => global::System.Collections.Generic.EqualityComparer<long>.Default.Equals(_longcase_value, other._longcase_value),
            Tags.ByteCase => global::System.Collections.Generic.EqualityComparer<byte>.Default.Equals(_bytecase_value, other._bytecase_value),
            Tags.FloatCase => global::System.Collections.Generic.EqualityComparer<float>.Default.Equals(_floatcase_value, other._floatcase_value),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Mixed other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.IntCase => global::System.HashCode.Combine(_tag, _intcase_value),
            Tags.LongCase => global::System.HashCode.Combine(_tag, _longcase_value),
            Tags.ByteCase => global::System.HashCode.Combine(_tag, _bytecase_value),
            Tags.FloatCase => global::System.HashCode.Combine(_tag, _floatcase_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Mixed left, Mixed right) => left.Equals(right);
    public static bool operator !=(Mixed left, Mixed right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.IntCase => $"IntCase({_intcase_value})",
            Tags.LongCase => $"LongCase({_longcase_value})",
            Tags.ByteCase => $"ByteCase({_bytecase_value})",
            Tags.FloatCase => $"FloatCase({_floatcase_value})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
