//HintName: NumberUnion.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  value        double       8B  (Celsius)
/// @ 8..16  value        double       8B  (Fahrenheit)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Celsius       8B
/// Fahrenheit    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
public readonly partial struct NumberUnion : global::System.IEquatable<NumberUnion>
{
    private const byte TagCelsius = 1;
    private const byte TagFahrenheit = 2;

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly byte _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _celsius_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _fahrenheit_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public NumberUnion() { }

    public static partial NumberUnion Celsius(double value)
    {
        var result = default(NumberUnion);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagCelsius;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._celsius_value) = value;
        return result;
    }

    public static partial NumberUnion Fahrenheit(double value)
    {
        var result = default(NumberUnion);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagFahrenheit;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._fahrenheit_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsCelsius => _tag == TagCelsius;
    public bool IsFahrenheit => _tag == TagFahrenheit;

    public double CelsiusValue
    {
        get
        {
            if (_tag != TagCelsius) ThrowInvalidCase(nameof(Celsius));
            return _celsius_value;
        }
    }
    public double FahrenheitValue
    {
        get
        {
            if (_tag != TagFahrenheit) ThrowInvalidCase(nameof(Fahrenheit));
            return _fahrenheit_value;
        }
    }

    public bool TryGetCelsius(out double value)
    {
        if (_tag == TagCelsius)
        {
            value = _celsius_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetFahrenheit(out double value)
    {
        if (_tag == TagFahrenheit)
        {
            value = _fahrenheit_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> celsius, global::System.Func<double, TResult> fahrenheit)
    {
        return _tag switch
        {
            TagCelsius => celsius(_celsius_value),
            TagFahrenheit => fahrenheit(_fahrenheit_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> celsius, global::System.Action<double> fahrenheit)
    {
        switch (_tag)
        {
            case TagCelsius: celsius(_celsius_value); break;
            case TagFahrenheit: fahrenheit(_fahrenheit_value); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public bool Equals(NumberUnion other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagCelsius => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_celsius_value, other._celsius_value),
            TagFahrenheit => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_fahrenheit_value, other._fahrenheit_value),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is NumberUnion other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagCelsius => global::System.HashCode.Combine(_tag, _celsius_value),
            TagFahrenheit => global::System.HashCode.Combine(_tag, _fahrenheit_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(NumberUnion left, NumberUnion right) => left.Equals(right);
    public static bool operator !=(NumberUnion left, NumberUnion right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagCelsius => $"Celsius({_celsius_value})",
            TagFahrenheit => $"Fahrenheit({_fahrenheit_value})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
