//HintName: Outer.Inner.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

partial class Outer
{
    /// <summary>
    /// Struct union with 2 variants.
    /// </summary>
    /// <remarks>
    /// <para><b>8 bytes</b> · align 4 · 3B padding</para>
    /// <code>
    /// @0..1  _tag         byte         1B
    /// @1..4  ---          padding      3B
    /// @4..8  x            int          4B  (A)
    /// @4..8  y            int          4B  (B)
    /// </code>
    /// <para><b>Variants</b></para>
    /// <code>
    /// A    4B
    /// B    4B
    /// </code>
    /// </remarks>
    [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 8)]
    public readonly partial struct Inner : global::System.IEquatable<Inner>
    {
        public enum Tags : byte
        {
            Default = 0,
            A = 1,
            B = 2,
        }

        [global::System.Runtime.InteropServices.FieldOffset(0)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly Tags _tag;

        [global::System.Runtime.InteropServices.FieldOffset(4)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly int _a_x;

        [global::System.Runtime.InteropServices.FieldOffset(4)]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        private readonly int _b_y;

        [global::System.Obsolete("Use factory methods instead.", true)]
        public Inner() { }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static partial Inner A(int x)
        {
            var result = default(Inner);
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.A;
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._a_x) = x;
            return result;
        }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static partial Inner B(int y)
        {
            var result = default(Inner);
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.B;
            global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._b_y) = y;
            return result;
        }

        /// <summary>Gets the tag value identifying which variant is active.</summary>
        public Tags Tag => _tag;

        /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
        public bool IsDefault => _tag == Tags.Default;

        public bool IsA => _tag == Tags.A;
        public bool IsB => _tag == Tags.B;

        public int AX
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_tag != Tags.A) ThrowInvalidCase(nameof(A));
                return _a_x;
            }
        }
        public int BY
        {
            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            get
            {
                if (_tag != Tags.B) ThrowInvalidCase(nameof(B));
                return _b_y;
            }
        }

        public bool TryGetA(out int x)
        {
            if (_tag == Tags.A)
            {
                x = _a_x;
                return true;
            }

            x = default!;
            return false;
        }

        public bool TryGetB(out int y)
        {
            if (_tag == Tags.B)
            {
                y = _b_y;
                return true;
            }

            y = default!;
            return false;
        }

        public TResult Match<TResult>(global::System.Func<int, TResult> a, global::System.Func<int, TResult> b)
        {
            return _tag switch
            {
                Tags.A => a(_a_x),
                Tags.B => b(_b_y),
                _ => ThrowUnknownTag<TResult>()
            };
        }

        public TResult Match<TState, TResult>(TState state, global::System.Func<TState, int, TResult> a, global::System.Func<TState, int, TResult> b)
        {
            return _tag switch
            {
                Tags.A => a(state, _a_x),
                Tags.B => b(state, _b_y),
                _ => ThrowUnknownTag<TResult>()
            };
        }

        public void Match(global::System.Action<int> a, global::System.Action<int> b)
        {
            switch (_tag)
            {
                case Tags.A: a(_a_x); break;
                case Tags.B: b(_b_y); break;
                default: ThrowUnknownTag(); break;
            }
        }

        public void Match<TState>(TState state, global::System.Action<TState, int> a, global::System.Action<TState, int> b)
        {
            switch (_tag)
            {
                case Tags.A: a(state, _a_x); break;
                case Tags.B: b(state, _b_y); break;
                default: ThrowUnknownTag(); break;
            }
        }

        public bool Equals(Inner other)
        {
            if (_tag != other._tag) return false;
            return _tag switch
            {
                Tags.A => _a_x == other._a_x,
                Tags.B => _b_y == other._b_y,
                _ => true
            };
        }

        public override bool Equals(object? obj) => obj is Inner other && Equals(other);

        public override int GetHashCode()
        {
            return _tag switch
            {
                Tags.A => global::System.HashCode.Combine(_tag, _a_x),
                Tags.B => global::System.HashCode.Combine(_tag, _b_y),
                _ => _tag.GetHashCode()
            };
        }

        public static bool operator ==(Inner left, Inner right) => left.Equals(right);
        public static bool operator !=(Inner left, Inner right) => !left.Equals(right);

        public override string ToString()
        {
            return _tag switch
            {
                Tags.A => $"A({_a_x})",
                Tags.B => $"B({_b_y})",
                Tags.Default => "Default",
                _ => "<invalid>"
            };
        }

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static void ThrowInvalidCase(string caseName) =>
            throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static TResult ThrowUnknownTag<TResult>() =>
            throw new global::System.InvalidOperationException("Unknown union tag.");

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
        private static void ThrowUnknownTag() =>
            throw new global::System.InvalidOperationException("Unknown union tag.");
    }
}
