//HintName: InternalShape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// @ 8..16  w            double       8B  (Rect)
/// @16..24  h            double       8B  (Rect)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle    8B
/// Rect     16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
internal readonly partial struct InternalShape : global::System.IEquatable<InternalShape>
{
    private const byte TagCircle = 1;
    private const byte TagRect = 2;

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly byte _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _circle_radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly double _rect_w;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    private readonly double _rect_h;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public InternalShape() { }

    public static partial InternalShape Circle(double radius)
    {
        var result = default(InternalShape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagCircle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    public static partial InternalShape Rect(double w, double h)
    {
        var result = default(InternalShape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagRect;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rect_w) = w;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rect_h) = h;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsCircle => _tag == TagCircle;
    public bool IsRect => _tag == TagRect;

    public double CircleRadius
    {
        get
        {
            if (_tag != TagCircle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }
    public double RectW
    {
        get
        {
            if (_tag != TagRect) ThrowInvalidCase(nameof(Rect));
            return _rect_w;
        }
    }
    public double RectH
    {
        get
        {
            if (_tag != TagRect) ThrowInvalidCase(nameof(Rect));
            return _rect_h;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == TagCircle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public bool TryGetRect(out double w, out double h)
    {
        if (_tag == TagRect)
        {
            w = _rect_w;
            h = _rect_h;
            return true;
        }

        w = default!;
        h = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, double, TResult> rect)
    {
        return _tag switch
        {
            TagCircle => circle(_circle_radius),
            TagRect => rect(_rect_w, _rect_h),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double, double> rect)
    {
        switch (_tag)
        {
            case TagCircle: circle(_circle_radius); break;
            case TagRect: rect(_rect_w, _rect_h); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public static implicit operator InternalShape(double value) => Circle(value);

    public bool Equals(InternalShape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagCircle => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_circle_radius, other._circle_radius),
            TagRect => global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rect_w, other._rect_w) && global::System.Collections.Generic.EqualityComparer<double>.Default.Equals(_rect_h, other._rect_h),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is InternalShape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagCircle => global::System.HashCode.Combine(_tag, _circle_radius),
            TagRect => global::System.HashCode.Combine(_tag, _rect_w, _rect_h),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(InternalShape left, InternalShape right) => left.Equals(right);
    public static bool operator !=(InternalShape left, InternalShape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagCircle => $"Circle({_circle_radius})",
            TagRect => $"Rect({_rect_w}, {_rect_h})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
