//HintName: BigVariant.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>36 bytes</b> · align 4 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  a            int          4B  (Many)
/// @ 4.. 8  x            int          4B  (Small)
/// @ 8..12  b            int          4B  (Many)
/// @12..16  c            int          4B  (Many)
/// @16..20  d            int          4B  (Many)
/// @20..24  e            int          4B  (Many)
/// @24..28  f            int          4B  (Many)
/// @28..32  g            int          4B  (Many)
/// @32..36  h            int          4B  (Many)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Many    32B
/// Small    4B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 36)]
public readonly partial struct BigVariant : global::System.IEquatable<BigVariant>
{
    public enum Tags : byte
    {
        Default = 0,
        Many = 1,
        Small = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_a;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_b;

    [global::System.Runtime.InteropServices.FieldOffset(12)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_c;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_d;

    [global::System.Runtime.InteropServices.FieldOffset(20)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_e;

    [global::System.Runtime.InteropServices.FieldOffset(24)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_f;

    [global::System.Runtime.InteropServices.FieldOffset(28)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_g;

    [global::System.Runtime.InteropServices.FieldOffset(32)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _many_h;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _small_x;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public BigVariant() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial BigVariant Many(int a, int b, int c, int d, int e, int f, int g, int h)
    {
        var result = default(BigVariant);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Many;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_a) = a;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_b) = b;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_c) = c;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_d) = d;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_e) = e;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_f) = f;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_g) = g;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._many_h) = h;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial BigVariant Small(int x)
    {
        var result = default(BigVariant);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Small;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._small_x) = x;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsMany => _tag == Tags.Many;
    public bool IsSmall => _tag == Tags.Small;

    public int ManyA
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_a;
        }
    }
    public int ManyB
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_b;
        }
    }
    public int ManyC
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_c;
        }
    }
    public int ManyD
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_d;
        }
    }
    public int ManyE
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_e;
        }
    }
    public int ManyF
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_f;
        }
    }
    public int ManyG
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_g;
        }
    }
    public int ManyH
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Many) ThrowInvalidCase(nameof(Many));
            return _many_h;
        }
    }
    public int SmallX
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Small) ThrowInvalidCase(nameof(Small));
            return _small_x;
        }
    }

    public bool TryGetMany(out int a, out int b, out int c, out int d, out int e, out int f, out int g, out int h)
    {
        if (_tag == Tags.Many)
        {
            a = _many_a;
            b = _many_b;
            c = _many_c;
            d = _many_d;
            e = _many_e;
            f = _many_f;
            g = _many_g;
            h = _many_h;
            return true;
        }

        a = default!;
        b = default!;
        c = default!;
        d = default!;
        e = default!;
        f = default!;
        g = default!;
        h = default!;
        return false;
    }

    public bool TryGetSmall(out int x)
    {
        if (_tag == Tags.Small)
        {
            x = _small_x;
            return true;
        }

        x = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<int, int, int, int, int, int, int, int, TResult> many, global::System.Func<int, TResult> small)
    {
        return _tag switch
        {
            Tags.Many => many(_many_a, _many_b, _many_c, _many_d, _many_e, _many_f, _many_g, _many_h),
            Tags.Small => small(_small_x),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int, int, int, int, int, int, int, int> many, global::System.Action<int> small)
    {
        switch (_tag)
        {
            case Tags.Many: many(_many_a, _many_b, _many_c, _many_d, _many_e, _many_f, _many_g, _many_h); break;
            case Tags.Small: small(_small_x); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator BigVariant(int value) => Small(value);

    public bool Equals(BigVariant other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Many => _many_a == other._many_a && _many_b == other._many_b && _many_c == other._many_c && _many_d == other._many_d && _many_e == other._many_e && _many_f == other._many_f && _many_g == other._many_g && _many_h == other._many_h,
            Tags.Small => _small_x == other._small_x,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is BigVariant other && Equals(other);

    public override int GetHashCode()
    {
        var hash = new global::System.HashCode();
        hash.Add(_tag);
        switch (_tag)
        {
            case Tags.Many:
                hash.Add(_many_a);
                hash.Add(_many_b);
                hash.Add(_many_c);
                hash.Add(_many_d);
                hash.Add(_many_e);
                hash.Add(_many_f);
                hash.Add(_many_g);
                hash.Add(_many_h);
                break;
            case Tags.Small:
                hash.Add(_small_x);
                break;
        }
        return hash.ToHashCode();
    }

    public static bool operator ==(BigVariant left, BigVariant right) => left.Equals(right);
    public static bool operator !=(BigVariant left, BigVariant right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Many => $"Many({_many_a}, {_many_b}, {_many_c}, {_many_d}, {_many_e}, {_many_f}, {_many_g}, {_many_h})",
            Tags.Small => $"Small({_small_x})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
