//HintName: Option.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

public readonly partial struct Option<T> : global::System.IEquatable<Option<T>>
    where T : struct, unmanaged
{
    private const byte TagSome = 1;
    private const byte TagNone = 2;

    private readonly byte _tag;
    private readonly T _some_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Option() { }

    public static partial Option<T> Some(T value)
    {
        var result = default(Option<T>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagSome;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._some_value) = value;
        return result;
    }

    public static partial Option<T> None()
    {
        var result = default(Option<T>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagNone;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsSome => _tag == TagSome;
    public bool IsNone => _tag == TagNone;

    public T SomeValue
    {
        get
        {
            if (_tag != TagSome) ThrowInvalidCase(nameof(Some));
            return _some_value;
        }
    }

    public bool TryGetSome(out T value)
    {
        if (_tag == TagSome)
        {
            value = _some_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetNone() => _tag == TagNone;

    public TResult Match<TResult>(global::System.Func<T, TResult> some, global::System.Func<TResult> none)
    {
        return _tag switch
        {
            TagSome => some(_some_value),
            TagNone => none(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<T> some, global::System.Action none)
    {
        switch (_tag)
        {
            case TagSome: some(_some_value); break;
            case TagNone: none(); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public static implicit operator Option<T>(T value) => Some(value);

    public bool Equals(Option<T> other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagSome => global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(_some_value, other._some_value),
            TagNone => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Option<T> other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagSome => global::System.HashCode.Combine(_tag, _some_value),
            TagNone => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Option<T> left, Option<T> right) => left.Equals(right);
    public static bool operator !=(Option<T> left, Option<T> right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagSome => $"Some({_some_value})",
            TagNone => "None",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
