//HintName: Option.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

public readonly partial struct Option<T> : global::System.IEquatable<Option<T>>
    where T : struct, unmanaged
{
    public enum Tags : byte
    {
        Default = 0,
        Some = 1,
        None = 2,
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly T _some_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Option() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Option<T> Some(T value)
    {
        var result = default(Option<T>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Some;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._some_value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Option<T> None()
    {
        var result = default(Option<T>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.None;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsSome => _tag == Tags.Some;
    public bool IsNone => _tag == Tags.None;

    public T SomeValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Some) ThrowInvalidCase(nameof(Some));
            return _some_value;
        }
    }

    public bool TryGetSome(out T value)
    {
        if (_tag == Tags.Some)
        {
            value = _some_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetNone() => _tag == Tags.None;

    public TResult Match<TResult>(global::System.Func<T, TResult> some, global::System.Func<TResult> none)
    {
        return _tag switch
        {
            Tags.Some => some(_some_value),
            Tags.None => none(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, T, TResult> some, global::System.Func<TState, TResult> none)
    {
        return _tag switch
        {
            Tags.Some => some(state, _some_value),
            Tags.None => none(state),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<T> some, global::System.Action none)
    {
        switch (_tag)
        {
            case Tags.Some: some(_some_value); break;
            case Tags.None: none(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, T> some, global::System.Action<TState> none)
    {
        switch (_tag)
        {
            case Tags.Some: some(state, _some_value); break;
            case Tags.None: none(state); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Option<T>(T value) => Some(value);

    public bool Equals(Option<T> other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Some => global::System.Collections.Generic.EqualityComparer<T>.Default.Equals(_some_value, other._some_value),
            Tags.None => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Option<T> other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Some => global::System.HashCode.Combine(_tag, _some_value),
            Tags.None => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Option<T> left, Option<T> right) => left.Equals(right);
    public static bool operator !=(Option<T> left, Option<T> right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Some => $"Some({_some_value})",
            Tags.None => "None",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
