//HintName: Result.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

public readonly partial struct Result<TOk, TError> : global::System.IEquatable<Result<TOk, TError>>
{
    private const byte TagOk = 1;
    private const byte TagError = 2;

    private readonly byte _tag;
    private readonly TOk _ok_value;
    private readonly TError _error_error;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Result() { }

    public static partial Result<TOk, TError> Ok(TOk value)
    {
        var result = default(Result<TOk, TError>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagOk;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._ok_value) = value;
        return result;
    }

    public static partial Result<TOk, TError> Error(TError error)
    {
        var result = default(Result<TOk, TError>);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagError;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._error_error) = error;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsOk => _tag == TagOk;
    public bool IsError => _tag == TagError;

    public TOk OkValue
    {
        get
        {
            if (_tag != TagOk) ThrowInvalidCase(nameof(Ok));
            return _ok_value;
        }
    }
    public TError ErrorError
    {
        get
        {
            if (_tag != TagError) ThrowInvalidCase(nameof(Error));
            return _error_error;
        }
    }

    public bool TryGetOk(out TOk value)
    {
        if (_tag == TagOk)
        {
            value = _ok_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetError(out TError error)
    {
        if (_tag == TagError)
        {
            error = _error_error;
            return true;
        }

        error = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<TOk, TResult> ok, global::System.Func<TError, TResult> error)
    {
        return _tag switch
        {
            TagOk => ok(_ok_value),
            TagError => error(_error_error),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<TOk> ok, global::System.Action<TError> error)
    {
        switch (_tag)
        {
            case TagOk: ok(_ok_value); break;
            case TagError: error(_error_error); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public static implicit operator Result<TOk, TError>(TOk value) => Ok(value);
    public static implicit operator Result<TOk, TError>(TError value) => Error(value);

    public bool Equals(Result<TOk, TError> other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagOk => global::System.Collections.Generic.EqualityComparer<TOk>.Default.Equals(_ok_value, other._ok_value),
            TagError => global::System.Collections.Generic.EqualityComparer<TError>.Default.Equals(_error_error, other._error_error),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Result<TOk, TError> other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagOk => global::System.HashCode.Combine(_tag, _ok_value),
            TagError => global::System.HashCode.Combine(_tag, _error_error),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Result<TOk, TError> left, Result<TOk, TError> right) => left.Equals(right);
    public static bool operator !=(Result<TOk, TError> left, Result<TOk, TError> right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagOk => $"Ok({_ok_value})",
            TagError => $"Error({_error_error})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
