//HintName: MyApp.Outer.Inner.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

namespace MyApp
{
    partial class Outer
    {
        /// <summary>
        /// Struct union with 1 variant.
        /// </summary>
        /// <remarks>
        /// <para><b>8 bytes</b> · align 4 · 3B padding</para>
        /// <code>
        /// @0..1  _tag         byte         1B
        /// @1..4  ---          padding      3B
        /// @4..8  x            int          4B  (Value)
        /// </code>
        /// <para><b>Variants</b></para>
        /// <code>
        /// Value    4B
        /// </code>
        /// </remarks>
        [global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 8)]
        [global::System.Runtime.CompilerServices.Union]
        public readonly partial struct Inner : global::System.IEquatable<Inner>, global::MyApp.Outer.Inner.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
        {
            public enum Tags : byte
            {
                Default = 0,
                Value = 1,
            }

            [global::System.Runtime.InteropServices.FieldOffset(0)]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            private readonly Tags _tag;

            [global::System.Runtime.InteropServices.FieldOffset(4)]
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            private readonly int _value_x;

            public static class Cases
            {
                public readonly struct Value
                {
                    public int X { get; }

                    public Value(int x)
                    {
                        X = x;
                    }

                    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                    public void Deconstruct(out int x)
                    {
                        x = X;
                    }
                }

            }

            /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            public interface IUnionMembers
            {
                object? Value { get; }

                bool HasValue { get; }

                bool TryGetValue(out Cases.Value value);

                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                public static Inner Create(Cases.Value value) => global::MyApp.Outer.Inner.Value(value.X);
            }

            [global::System.Obsolete("Use factory methods instead.", true)]
            public Inner() { }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public static partial Inner Value(int x)
            {
                var result = default(Inner);
                global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Value;
                global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._value_x) = x;
                return result;
            }

            /// <summary>Gets the tag value identifying which variant is active.</summary>
            public Tags Tag => _tag;

            /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
            public bool IsDefault => _tag == Tags.Default;

            public bool IsValue => _tag == Tags.Value;

            public int ValueX
            {
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                get
                {
                    if (_tag != Tags.Value) ThrowInvalidCase(nameof(Value));
                    return _value_x;
                }
            }

            public bool TryGetValue(out int x)
            {
                if (_tag == Tags.Value)
                {
                    x = _value_x;
                    return true;
                }

                x = default!;
                return false;
            }

            public TResult Match<TResult>(global::System.Func<int, TResult> value)
            {
                return _tag switch
                {
                    Tags.Value => value(_value_x),
                    _ => ThrowUnknownTag<TResult>()
                };
            }

            public TResult Match<TState, TResult>(TState state, global::System.Func<TState, int, TResult> value)
            {
                return _tag switch
                {
                    Tags.Value => value(state, _value_x),
                    _ => ThrowUnknownTag<TResult>()
                };
            }

            public void Match(global::System.Action<int> value)
            {
                switch (_tag)
                {
                    case Tags.Value: value(_value_x); break;
                    default: ThrowUnknownTag(); break;
                }
            }

            public void Match<TState>(TState state, global::System.Action<TState, int> value)
            {
                switch (_tag)
                {
                    case Tags.Value: value(state, _value_x); break;
                    default: ThrowUnknownTag(); break;
                }
            }

            public static implicit operator Inner(int value) => Value(value);

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            private object? GetUnionValue()
            {
                switch (_tag)
                {
                    case Tags.Value: return new Cases.Value(_value_x);
                    default: return null;
                }
            }

            object? global::MyApp.Outer.Inner.IUnionMembers.Value
            {
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                get => GetUnionValue();
            }

            object? global::System.Runtime.CompilerServices.IUnion.Value
            {
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                get => GetUnionValue();
            }

            bool global::MyApp.Outer.Inner.IUnionMembers.HasValue
            {
                [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
                get => _tag != Tags.Default;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            bool global::MyApp.Outer.Inner.IUnionMembers.TryGetValue(out Cases.Value value)
            {
                if (_tag == Tags.Value)
                {
                    value = new Cases.Value(_value_x);
                    return true;
                }

                value = default;
                return false;
            }

            public bool Equals(Inner other)
            {
                if (_tag != other._tag) return false;
                return _tag switch
                {
                    Tags.Value => _value_x == other._value_x,
                    _ => true
                };
            }

            public override bool Equals(object? obj) => obj is Inner other && Equals(other);

            public override int GetHashCode()
            {
                return _tag switch
                {
                    Tags.Value => global::System.HashCode.Combine(_tag, _value_x),
                    _ => _tag.GetHashCode()
                };
            }

            public static bool operator ==(Inner left, Inner right) => left.Equals(right);
            public static bool operator !=(Inner left, Inner right) => !left.Equals(right);

            public override string ToString()
            {
                return _tag switch
                {
                    Tags.Value => $"Value({_value_x})",
                    Tags.Default => "Default",
                    _ => "<invalid>"
                };
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            private static void ThrowInvalidCase(string caseName) =>
                throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            private static TResult ThrowUnknownTag<TResult>() =>
                throw new global::System.InvalidOperationException("Unknown union tag.");

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
            private static void ThrowUnknownTag() =>
                throw new global::System.InvalidOperationException("Unknown union tag.");
        }
    }
}
