//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// @ 8..16  length       double       8B  (Rectangle)
/// @16..24  width        double       8B  (Rectangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle       8B
/// Rectangle   16B
/// Empty        0B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Shape : global::System.IEquatable<Shape>, global::Shape.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
        Rectangle = 2,
        Empty = 3,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_length;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_width;

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private static readonly object s_boxed_empty = new Cases.Empty();

    public static class Cases
    {
        public readonly struct Circle
        {
            public double Radius { get; }

            public Circle(double radius)
            {
                Radius = radius;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out double radius)
            {
                radius = Radius;
            }
        }

        public readonly struct Rectangle
        {
            public double Length { get; }
            public double Width { get; }

            public Rectangle(double length, double width)
            {
                Length = length;
                Width = width;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out double length, out double width)
            {
                length = Length;
                width = Width;
            }
        }

        public readonly struct Empty
        {
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.Circle value);

        bool TryGetValue(out Cases.Rectangle value);

        bool TryGetValue(out Cases.Empty value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Circle value) => global::Shape.Circle(value.Radius);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Rectangle value) => global::Shape.Rectangle(value.Length, value.Width);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Empty value) => global::Shape.Empty();
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Rectangle(double length, double width)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Rectangle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_length) = length;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_width) = width;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Empty()
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Empty;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;
    public bool IsRectangle => _tag == Tags.Rectangle;
    public bool IsEmpty => _tag == Tags.Empty;

    public double CircleRadius
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }
    public double RectangleLength
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_length;
        }
    }
    public double RectangleWidth
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_width;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == Tags.Circle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public bool TryGetRectangle(out double length, out double width)
    {
        if (_tag == Tags.Rectangle)
        {
            length = _rectangle_length;
            width = _rectangle_width;
            return true;
        }

        length = default!;
        width = default!;
        return false;
    }

    public bool TryGetEmpty() => _tag == Tags.Empty;

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, double, TResult> rectangle, global::System.Func<TResult> empty)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_radius),
            Tags.Rectangle => rectangle(_rectangle_length, _rectangle_width),
            Tags.Empty => empty(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, double, TResult> circle, global::System.Func<TState, double, double, TResult> rectangle, global::System.Func<TState, TResult> empty)
    {
        return _tag switch
        {
            Tags.Circle => circle(state, _circle_radius),
            Tags.Rectangle => rectangle(state, _rectangle_length, _rectangle_width),
            Tags.Empty => empty(state),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double, double> rectangle, global::System.Action empty)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_radius); break;
            case Tags.Rectangle: rectangle(_rectangle_length, _rectangle_width); break;
            case Tags.Empty: empty(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, double> circle, global::System.Action<TState, double, double> rectangle, global::System.Action<TState> empty)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(state, _circle_radius); break;
            case Tags.Rectangle: rectangle(state, _rectangle_length, _rectangle_width); break;
            case Tags.Empty: empty(state); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Shape(double value) => Circle(value);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.Circle: return new Cases.Circle(_circle_radius);
            case Tags.Rectangle: return new Cases.Rectangle(_rectangle_length, _rectangle_width);
            case Tags.Empty: return s_boxed_empty;
            default: return null;
        }
    }

    object? global::Shape.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Shape.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Circle value)
    {
        if (_tag == Tags.Circle)
        {
            value = new Cases.Circle(_circle_radius);
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Rectangle value)
    {
        if (_tag == Tags.Rectangle)
        {
            value = new Cases.Rectangle(_rectangle_length, _rectangle_width);
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Empty value)
    {
        if (_tag == Tags.Empty)
        {
            value = default;
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Circle => _circle_radius.Equals(other._circle_radius),
            Tags.Rectangle => _rectangle_length.Equals(other._rectangle_length) && _rectangle_width.Equals(other._rectangle_width),
            Tags.Empty => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Circle => global::System.HashCode.Combine(_tag, _circle_radius),
            Tags.Rectangle => global::System.HashCode.Combine(_tag, _rectangle_length, _rectangle_width),
            Tags.Empty => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_radius})",
            Tags.Rectangle => $"Rectangle({_rectangle_length}, {_rectangle_width})",
            Tags.Empty => "Empty",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
