//HintName: Resource.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  value        int          4B  (Inline)
/// @ 8..16  stream       FileStream   8B  (File)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// File      8B
/// Inline    4B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Resource : global::System.IEquatable<Resource>, global::System.IDisposable, global::System.IAsyncDisposable, global::Resource.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        File = 1,
        Inline = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.IO.FileStream _file_stream;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _inline_value;

    public static class Cases
    {
        public readonly struct File
        {
            public global::System.IO.FileStream Stream { get; }

            public File(global::System.IO.FileStream stream)
            {
                Stream = stream;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out global::System.IO.FileStream stream)
            {
                stream = Stream;
            }
        }

        public readonly struct Inline
        {
            public int Value { get; }

            public Inline(int value)
            {
                Value = value;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out int value)
            {
                value = Value;
            }
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.File value);

        bool TryGetValue(out Cases.Inline value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Resource Create(Cases.File value) => global::Resource.File(value.Stream);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Resource Create(Cases.Inline value) => global::Resource.Inline(value.Value);
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Resource() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource File(global::System.IO.FileStream stream)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.File;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._file_stream) = stream;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Resource Inline(int value)
    {
        var result = default(Resource);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Inline;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._inline_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsFile => _tag == Tags.File;
    public bool IsInline => _tag == Tags.Inline;

    public global::System.IO.FileStream FileStream
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.File) ThrowInvalidCase(nameof(File));
            return _file_stream;
        }
    }
    public int InlineValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Inline) ThrowInvalidCase(nameof(Inline));
            return _inline_value;
        }
    }

    public bool TryGetFile(out global::System.IO.FileStream stream)
    {
        if (_tag == Tags.File)
        {
            stream = _file_stream;
            return true;
        }

        stream = default!;
        return false;
    }

    public bool TryGetInline(out int value)
    {
        if (_tag == Tags.Inline)
        {
            value = _inline_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::System.IO.FileStream, TResult> file, global::System.Func<int, TResult> inline)
    {
        return _tag switch
        {
            Tags.File => file(_file_stream),
            Tags.Inline => inline(_inline_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.IO.FileStream, TResult> file, global::System.Func<TState, int, TResult> inline)
    {
        return _tag switch
        {
            Tags.File => file(state, _file_stream),
            Tags.Inline => inline(state, _inline_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.IO.FileStream> file, global::System.Action<int> inline)
    {
        switch (_tag)
        {
            case Tags.File: file(_file_stream); break;
            case Tags.Inline: inline(_inline_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.IO.FileStream> file, global::System.Action<TState, int> inline)
    {
        switch (_tag)
        {
            case Tags.File: file(state, _file_stream); break;
            case Tags.Inline: inline(state, _inline_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Resource(global::System.IO.FileStream value) => File(value);
    public static implicit operator Resource(int value) => Inline(value);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.File: return new Cases.File(_file_stream);
            case Tags.Inline: return new Cases.Inline(_inline_value);
            default: return null;
        }
    }

    object? global::Resource.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Resource.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Resource.IUnionMembers.TryGetValue(out Cases.File value)
    {
        if (_tag == Tags.File)
        {
            value = new Cases.File(_file_stream);
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Resource.IUnionMembers.TryGetValue(out Cases.Inline value)
    {
        if (_tag == Tags.Inline)
        {
            value = new Cases.Inline(_inline_value);
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Resource other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.File => global::System.Collections.Generic.EqualityComparer<global::System.IO.FileStream>.Default.Equals(_file_stream, other._file_stream),
            Tags.Inline => _inline_value == other._inline_value,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Resource other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.File => global::System.HashCode.Combine(_tag, _file_stream),
            Tags.Inline => global::System.HashCode.Combine(_tag, _inline_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Resource left, Resource right) => left.Equals(right);
    public static bool operator !=(Resource left, Resource right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.File => $"File({_file_stream})",
            Tags.Inline => $"Inline({_inline_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    /// <summary>Disposes the active variant's IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public void Dispose()
    {
        switch (_tag)
        {
            case Tags.File:
                _file_stream?.Dispose();
                break;
        }
    }

    /// <summary>Asynchronously disposes the active variant's IAsyncDisposable / IDisposable resources, if any. Safe to call on default and non-disposable variants.</summary>
    public async global::System.Threading.Tasks.ValueTask DisposeAsync()
    {
        switch (_tag)
        {
            case Tags.File:
                if (_file_stream is not null) await _file_stream.DisposeAsync().ConfigureAwait(false);
                break;
        }
    }

    /// <summary>Removes ownership of the File payload from <paramref name="self"/> and returns it. Sets <paramref name="self"/> to default so subsequent disposal is a no-op. Throws if the active variant is not File.</summary>
    public static global::System.IO.FileStream TakeFile(ref Resource self)
    {
        if (self._tag != Tags.File) ThrowInvalidCase(nameof(File));
        var value = self._file_stream;
        self = default;
        return value;
    }

    /// <summary>If the active variant is File, removes ownership of its payload, writes it to <paramref name="value"/>, sets <paramref name="self"/> to default, and returns true.</summary>
    public static bool TryTakeFile(ref Resource self, out global::System.IO.FileStream value)
    {
        if (self._tag == Tags.File)
        {
            value = self._file_stream;
            self = default;
            return true;
        }

        value = default!;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
