//HintName: Payload.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  value        int          4B  (Number)
/// @ 8..16  value        string       8B  (Text)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Number    4B
/// Text      8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Payload : global::System.IEquatable<Payload>, global::Payload.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        Number = 1,
        Text = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _number_value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly string _text_value;

    public static class Cases
    {
        public readonly struct Number
        {
            public int Value { get; }

            public Number(int value)
            {
                Value = value;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out int value)
            {
                value = Value;
            }
        }

        public readonly struct Text
        {
            public string Value { get; }

            public Text(string value)
            {
                Value = value;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out string value)
            {
                value = Value;
            }
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.Number value);

        bool TryGetValue(out Cases.Text value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Payload Create(Cases.Number value) => global::Payload.Number(value.Value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Payload Create(Cases.Text value) => global::Payload.Text(value.Value);
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Payload() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Payload Number(int value)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Number;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._number_value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Payload Text(string value)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Text;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._text_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsNumber => _tag == Tags.Number;
    public bool IsText => _tag == Tags.Text;

    public int NumberValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Number) ThrowInvalidCase(nameof(Number));
            return _number_value;
        }
    }
    public string TextValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Text) ThrowInvalidCase(nameof(Text));
            return _text_value;
        }
    }

    public bool TryGetNumber(out int value)
    {
        if (_tag == Tags.Number)
        {
            value = _number_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetText(out string value)
    {
        if (_tag == Tags.Text)
        {
            value = _text_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<int, TResult> number, global::System.Func<string, TResult> text)
    {
        return _tag switch
        {
            Tags.Number => number(_number_value),
            Tags.Text => text(_text_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, int, TResult> number, global::System.Func<TState, string, TResult> text)
    {
        return _tag switch
        {
            Tags.Number => number(state, _number_value),
            Tags.Text => text(state, _text_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<int> number, global::System.Action<string> text)
    {
        switch (_tag)
        {
            case Tags.Number: number(_number_value); break;
            case Tags.Text: text(_text_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, int> number, global::System.Action<TState, string> text)
    {
        switch (_tag)
        {
            case Tags.Number: number(state, _number_value); break;
            case Tags.Text: text(state, _text_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Payload(int value) => Number(value);
    public static implicit operator Payload(string value) => Text(value);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.Number: return new Cases.Number(_number_value);
            case Tags.Text: return new Cases.Text(_text_value);
            default: return null;
        }
    }

    object? global::Payload.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Payload.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Payload.IUnionMembers.TryGetValue(out Cases.Number value)
    {
        if (_tag == Tags.Number)
        {
            value = new Cases.Number(_number_value);
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Payload.IUnionMembers.TryGetValue(out Cases.Text value)
    {
        if (_tag == Tags.Text)
        {
            value = new Cases.Text(_text_value);
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Payload other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Number => _number_value == other._number_value,
            Tags.Text => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_text_value, other._text_value),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Payload other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Number => global::System.HashCode.Combine(_tag, _number_value),
            Tags.Text => global::System.HashCode.Combine(_tag, _text_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Payload left, Payload right) => left.Equals(right);
    public static bool operator !=(Payload left, Payload right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Number => $"Number({_number_value})",
            Tags.Text => $"Text({_text_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
