//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 1 variant.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Shape : global::System.IEquatable<Shape>, global::Shape.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_radius;

    public static class Cases
    {
        public readonly struct Circle
        {
            public double Radius { get; }

            public Circle(double radius)
            {
                Radius = radius;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out double radius)
            {
                radius = Radius;
            }
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.Circle value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Circle value) => global::Shape.Circle(value.Radius);
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;

    public double CircleRadius
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == Tags.Circle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_radius),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, double, TResult> circle)
    {
        return _tag switch
        {
            Tags.Circle => circle(state, _circle_radius),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_radius); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, double> circle)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(state, _circle_radius); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Shape(double value) => Circle(value);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.Circle: return new Cases.Circle(_circle_radius);
            default: return null;
        }
    }

    object? global::Shape.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Shape.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Circle value)
    {
        if (_tag == Tags.Circle)
        {
            value = new Cases.Circle(_circle_radius);
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Circle => _circle_radius.Equals(other._circle_radius),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Circle => global::System.HashCode.Combine(_tag, _circle_radius),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_radius})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
