//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>24 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  Radius       double       8B  (Circle)
/// @ 8..16  Length       double       8B  (Rectangle)
/// @16..24  Width        double       8B  (Rectangle)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle       8B
/// Rectangle   16B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 24)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Shape : global::System.IEquatable<Shape>, global::Shape.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
        Rectangle = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_Radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_Length;

    [global::System.Runtime.InteropServices.FieldOffset(16)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _rectangle_Width;

    public static class Cases
    {
        public readonly struct Circle
        {
            public double Radius { get; }

            public Circle(double radius)
            {
                Radius = radius;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out double radius)
            {
                radius = Radius;
            }
        }

        public readonly struct Rectangle
        {
            public double Length { get; }
            public double Width { get; }

            public Rectangle(double length, double width)
            {
                Length = length;
                Width = width;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out double length, out double width)
            {
                length = Length;
                width = Width;
            }
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.Circle value);

        bool TryGetValue(out Cases.Rectangle value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Circle value) => global::Shape.Circle(value.Radius);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Shape Create(Cases.Rectangle value) => global::Shape.Rectangle(value.Length, value.Width);
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_Radius) = radius;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static Shape Rectangle(double length, double width)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Rectangle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_Length) = length;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._rectangle_Width) = width;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;
    public bool IsRectangle => _tag == Tags.Rectangle;

    public double CircleRadius
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_Radius;
        }
    }
    public double RectangleLength
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_Length;
        }
    }
    public double RectangleWidth
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Rectangle) ThrowInvalidCase(nameof(Rectangle));
            return _rectangle_Width;
        }
    }

    public bool TryGetCircle(out double Radius)
    {
        if (_tag == Tags.Circle)
        {
            Radius = _circle_Radius;
            return true;
        }

        Radius = default!;
        return false;
    }

    public bool TryGetRectangle(out double Length, out double Width)
    {
        if (_tag == Tags.Rectangle)
        {
            Length = _rectangle_Length;
            Width = _rectangle_Width;
            return true;
        }

        Length = default!;
        Width = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, double, TResult> rectangle)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_Radius),
            Tags.Rectangle => rectangle(_rectangle_Length, _rectangle_Width),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, double, TResult> circle, global::System.Func<TState, double, double, TResult> rectangle)
    {
        return _tag switch
        {
            Tags.Circle => circle(state, _circle_Radius),
            Tags.Rectangle => rectangle(state, _rectangle_Length, _rectangle_Width),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double, double> rectangle)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_Radius); break;
            case Tags.Rectangle: rectangle(_rectangle_Length, _rectangle_Width); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, double> circle, global::System.Action<TState, double, double> rectangle)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(state, _circle_Radius); break;
            case Tags.Rectangle: rectangle(state, _rectangle_Length, _rectangle_Width); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Shape(double value) => Circle(value);

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.Circle: return new Cases.Circle(_circle_Radius);
            case Tags.Rectangle: return new Cases.Rectangle(_rectangle_Length, _rectangle_Width);
            default: return null;
        }
    }

    object? global::Shape.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Shape.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Circle value)
    {
        if (_tag == Tags.Circle)
        {
            value = new Cases.Circle(_circle_Radius);
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Shape.IUnionMembers.TryGetValue(out Cases.Rectangle value)
    {
        if (_tag == Tags.Rectangle)
        {
            value = new Cases.Rectangle(_rectangle_Length, _rectangle_Width);
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Shape other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Circle => _circle_Radius.Equals(other._circle_Radius),
            Tags.Rectangle => _rectangle_Length.Equals(other._rectangle_Length) && _rectangle_Width.Equals(other._rectangle_Width),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Shape other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Circle => global::System.HashCode.Combine(_tag, _circle_Radius),
            Tags.Rectangle => global::System.HashCode.Combine(_tag, _rectangle_Length, _rectangle_Width),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Shape left, Shape right) => left.Equals(right);
    public static bool operator !=(Shape left, Shape right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_Radius})",
            Tags.Rectangle => $"Rectangle({_rectangle_Length}, {_rectangle_Width})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
