//HintName: Signal.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>1 bytes</b> · align 1</para>
/// <code>
/// @0..1  _tag         byte         1B
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Start    0B
/// Stop     0B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 1)]
[global::System.Runtime.CompilerServices.Union]
public readonly partial struct Signal : global::System.IEquatable<Signal>, global::Signal.IUnionMembers, global::System.Runtime.CompilerServices.IUnion
{
    public enum Tags : byte
    {
        Default = 0,
        Start = 1,
        Stop = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private static readonly object s_boxed_start = new Cases.Start();

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private static readonly object s_boxed_stop = new Cases.Stop();

    public static class Cases
    {
        public readonly struct Start
        {
        }

        public readonly struct Stop
        {
        }

    }

    /// <summary>C# 15 union member provider for the containing union. Generated; do not use directly.</summary>
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    public interface IUnionMembers
    {
        object? Value { get; }

        bool HasValue { get; }

        bool TryGetValue(out Cases.Start value);

        bool TryGetValue(out Cases.Stop value);

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Signal Create(Cases.Start value) => global::Signal.Start();

        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        public static Signal Create(Cases.Stop value) => global::Signal.Stop();
    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Signal() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Signal Start()
    {
        var result = default(Signal);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Start;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Signal Stop()
    {
        var result = default(Signal);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Stop;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsStart => _tag == Tags.Start;
    public bool IsStop => _tag == Tags.Stop;


    public bool TryGetStart() => _tag == Tags.Start;

    public bool TryGetStop() => _tag == Tags.Stop;

    public TResult Match<TResult>(global::System.Func<TResult> start, global::System.Func<TResult> stop)
    {
        return _tag switch
        {
            Tags.Start => start(),
            Tags.Stop => stop(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, TResult> start, global::System.Func<TState, TResult> stop)
    {
        return _tag switch
        {
            Tags.Start => start(state),
            Tags.Stop => stop(state),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action start, global::System.Action stop)
    {
        switch (_tag)
        {
            case Tags.Start: start(); break;
            case Tags.Stop: stop(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState> start, global::System.Action<TState> stop)
    {
        switch (_tag)
        {
            case Tags.Start: start(state); break;
            case Tags.Stop: stop(state); break;
            default: ThrowUnknownTag(); break;
        }
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    private object? GetUnionValue()
    {
        switch (_tag)
        {
            case Tags.Start: return s_boxed_start;
            case Tags.Stop: return s_boxed_stop;
            default: return null;
        }
    }

    object? global::Signal.IUnionMembers.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    object? global::System.Runtime.CompilerServices.IUnion.Value
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => GetUnionValue();
    }

    bool global::Signal.IUnionMembers.HasValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get => _tag != Tags.Default;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Signal.IUnionMembers.TryGetValue(out Cases.Start value)
    {
        if (_tag == Tags.Start)
        {
            value = default;
            return true;
        }

        value = default;
        return false;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    bool global::Signal.IUnionMembers.TryGetValue(out Cases.Stop value)
    {
        if (_tag == Tags.Stop)
        {
            value = default;
            return true;
        }

        value = default;
        return false;
    }

    public bool Equals(Signal other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Start => true,
            Tags.Stop => true,
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Signal other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Start => global::System.HashCode.Combine(_tag),
            Tags.Stop => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Signal left, Signal right) => left.Equals(right);
    public static bool operator !=(Signal left, Signal right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Start => "Start",
            Tags.Stop => "Stop",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
