//HintName: Shape.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 2 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  radius       double       8B  (Circle)
/// @ 8..16  side         double       8B  (Square)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Circle    8B
/// Square    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit, Size = 16)]
public readonly partial struct Shape
{
    public enum Tags : byte
    {
        Default = 0,
        Circle = 1,
        Square = 2,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _circle_radius;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly double _square_side;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Shape() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Circle(double radius)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Circle;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._circle_radius) = radius;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Shape Square(double side)
    {
        var result = default(Shape);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Square;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._square_side) = side;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsCircle => _tag == Tags.Circle;
    public bool IsSquare => _tag == Tags.Square;

    public double CircleRadius
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Circle) ThrowInvalidCase(nameof(Circle));
            return _circle_radius;
        }
    }
    public double SquareSide
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Square) ThrowInvalidCase(nameof(Square));
            return _square_side;
        }
    }

    public bool TryGetCircle(out double radius)
    {
        if (_tag == Tags.Circle)
        {
            radius = _circle_radius;
            return true;
        }

        radius = default!;
        return false;
    }

    public bool TryGetSquare(out double side)
    {
        if (_tag == Tags.Square)
        {
            side = _square_side;
            return true;
        }

        side = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<double, TResult> circle, global::System.Func<double, TResult> square)
    {
        return _tag switch
        {
            Tags.Circle => circle(_circle_radius),
            Tags.Square => square(_square_side),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, double, TResult> circle, global::System.Func<TState, double, TResult> square)
    {
        return _tag switch
        {
            Tags.Circle => circle(state, _circle_radius),
            Tags.Square => square(state, _square_side),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<double> circle, global::System.Action<double> square)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(_circle_radius); break;
            case Tags.Square: square(_square_side); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, double> circle, global::System.Action<TState, double> square)
    {
        switch (_tag)
        {
            case Tags.Circle: circle(state, _circle_radius); break;
            case Tags.Square: square(state, _square_side); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Circle => $"Circle({_circle_radius})",
            Tags.Square => $"Square({_square_side})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
