//HintName: Payload.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor
#pragma warning disable CS0809 // obsolete Equals(object) override, unreachable for a ref struct

public readonly ref partial struct Payload : global::System.IEquatable<Payload>
{
    public enum Tags : byte
    {
        Default = 0,
        Bytes = 1,
        Number = 2,
        Empty = 3,
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.Span<byte> _bytes_data;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _number_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Payload() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Payload Bytes(global::System.Span<byte> data)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Bytes;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._bytes_data) = data;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Payload Number(int value)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Number;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._number_value) = value;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Payload Empty()
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Empty;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsBytes => _tag == Tags.Bytes;
    public bool IsNumber => _tag == Tags.Number;
    public bool IsEmpty => _tag == Tags.Empty;

    public global::System.Span<byte> BytesData
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Bytes) ThrowInvalidCase(nameof(Bytes));
            return _bytes_data;
        }
    }
    public int NumberValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Number) ThrowInvalidCase(nameof(Number));
            return _number_value;
        }
    }

    public bool TryGetBytes(out global::System.Span<byte> data)
    {
        if (_tag == Tags.Bytes)
        {
            data = _bytes_data;
            return true;
        }

        data = default!;
        return false;
    }

    public bool TryGetNumber(out int value)
    {
        if (_tag == Tags.Number)
        {
            value = _number_value;
            return true;
        }

        value = default!;
        return false;
    }

    public bool TryGetEmpty() => _tag == Tags.Empty;

    public TResult Match<TResult>(global::System.Func<global::System.Span<byte>, TResult> bytes, global::System.Func<int, TResult> number, global::System.Func<TResult> empty)
    {
        return _tag switch
        {
            Tags.Bytes => bytes(_bytes_data),
            Tags.Number => number(_number_value),
            Tags.Empty => empty(),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.Span<byte>, TResult> bytes, global::System.Func<TState, int, TResult> number, global::System.Func<TState, TResult> empty)
    {
        return _tag switch
        {
            Tags.Bytes => bytes(state, _bytes_data),
            Tags.Number => number(state, _number_value),
            Tags.Empty => empty(state),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.Span<byte>> bytes, global::System.Action<int> number, global::System.Action empty)
    {
        switch (_tag)
        {
            case Tags.Bytes: bytes(_bytes_data); break;
            case Tags.Number: number(_number_value); break;
            case Tags.Empty: empty(); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.Span<byte>> bytes, global::System.Action<TState, int> number, global::System.Action<TState> empty)
    {
        switch (_tag)
        {
            case Tags.Bytes: bytes(state, _bytes_data); break;
            case Tags.Number: number(state, _number_value); break;
            case Tags.Empty: empty(state); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Payload(global::System.Span<byte> value) => Bytes(value);
    public static implicit operator Payload(int value) => Number(value);

    public bool Equals(Payload other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Bytes => _bytes_data == other._bytes_data,
            Tags.Number => _number_value == other._number_value,
            Tags.Empty => true,
            _ => true
        };
    }

    [global::System.Obsolete("Equals(object) is not supported on Payload because a ref struct cannot be boxed. Use Equals(Payload) instead.", true)]
    public override bool Equals(object? obj) =>
        throw new global::System.NotSupportedException("Equals(object) is not supported on Payload because a ref struct cannot be boxed.");

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Bytes => global::System.HashCode.Combine(_tag),
            Tags.Number => global::System.HashCode.Combine(_tag, _number_value),
            Tags.Empty => global::System.HashCode.Combine(_tag),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Payload left, Payload right) => left.Equals(right);
    public static bool operator !=(Payload left, Payload right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Bytes => $"Bytes({_bytes_data.ToString()})",
            Tags.Number => $"Number({_number_value})",
            Tags.Empty => "Empty",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
