//HintName: Token.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor
#pragma warning disable CS0809 // obsolete Equals(object) override, unreachable for a ref struct

public readonly ref partial struct Token : global::System.IEquatable<Token>
{
    public enum Tags : byte
    {
        Default = 0,
        Text = 1,
        Number = 2,
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::System.ReadOnlySpan<char> _text_text;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _number_value;

    public static class Cases
    {
        public readonly ref struct Text
        {
            public global::System.ReadOnlySpan<char> Text { get; }

            public Text(global::System.ReadOnlySpan<char> text)
            {
                Text = text;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out global::System.ReadOnlySpan<char> text)
            {
                text = Text;
            }
        }

        public readonly struct Number
        {
            public int Value { get; }

            public Number(int value)
            {
                Value = value;
            }

            [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
            public void Deconstruct(out int value)
            {
                value = Value;
            }
        }

    }

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Token() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Token Text(global::System.ReadOnlySpan<char> text)
    {
        var result = default(Token);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Text;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._text_text) = text;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Token Number(int value)
    {
        var result = default(Token);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Number;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._number_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsText => _tag == Tags.Text;
    public bool IsNumber => _tag == Tags.Number;

    public Cases.Text AsText
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Text) ThrowInvalidCase(nameof(Text));
            return new Cases.Text(_text_text);
        }
    }
    public Cases.Number AsNumber
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Number) ThrowInvalidCase(nameof(Number));
            return new Cases.Number(_number_value);
        }
    }

    public bool TryGetText(out Cases.Text data)
    {
        if (_tag == Tags.Text)
        {
            data = new Cases.Text(_text_text);
            return true;
        }

        data = default;
        return false;
    }

    public bool TryGetNumber(out Cases.Number data)
    {
        if (_tag == Tags.Number)
        {
            data = new Cases.Number(_number_value);
            return true;
        }

        data = default;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::System.ReadOnlySpan<char>, TResult> text, global::System.Func<int, TResult> number)
    {
        return _tag switch
        {
            Tags.Text => text(_text_text),
            Tags.Number => number(_number_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::System.ReadOnlySpan<char>, TResult> text, global::System.Func<TState, int, TResult> number)
    {
        return _tag switch
        {
            Tags.Text => text(state, _text_text),
            Tags.Number => number(state, _number_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::System.ReadOnlySpan<char>> text, global::System.Action<int> number)
    {
        switch (_tag)
        {
            case Tags.Text: text(_text_text); break;
            case Tags.Number: number(_number_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::System.ReadOnlySpan<char>> text, global::System.Action<TState, int> number)
    {
        switch (_tag)
        {
            case Tags.Text: text(state, _text_text); break;
            case Tags.Number: number(state, _number_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Token(global::System.ReadOnlySpan<char> value) => Text(value);
    public static implicit operator Token(int value) => Number(value);

    public bool Equals(Token other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Text => _text_text == other._text_text,
            Tags.Number => _number_value == other._number_value,
            _ => true
        };
    }

    [global::System.Obsolete("Equals(object) is not supported on Token because a ref struct cannot be boxed. Use Equals(Token) instead.", true)]
    public override bool Equals(object? obj) =>
        throw new global::System.NotSupportedException("Equals(object) is not supported on Token because a ref struct cannot be boxed.");

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Text => global::System.HashCode.Combine(_tag),
            Tags.Number => global::System.HashCode.Combine(_tag, _number_value),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Token left, Token right) => left.Equals(right);
    public static bool operator !=(Token left, Token right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Text => $"Text({_text_text.ToString()})",
            Tags.Number => $"Number({_number_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
