//HintName: Holder.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor
#pragma warning disable CS0809 // obsolete Equals(object) override, unreachable for a ref struct

public readonly ref partial struct Holder
{
    public enum Tags : byte
    {
        Default = 0,
        Buf = 1,
        Number = 2,
    }

    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly Tags _tag;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly global::Buffer _buf_buffer;
    [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
    private readonly int _number_value;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Holder() { }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Holder Buf(global::Buffer buffer)
    {
        var result = default(Holder);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Buf;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._buf_buffer) = buffer;
        return result;
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
    public static partial Holder Number(int value)
    {
        var result = default(Holder);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Number;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._number_value) = value;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsBuf => _tag == Tags.Buf;
    public bool IsNumber => _tag == Tags.Number;

    public global::Buffer BufBuffer
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Buf) ThrowInvalidCase(nameof(Buf));
            return _buf_buffer;
        }
    }
    public int NumberValue
    {
        [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.AggressiveInlining)]
        get
        {
            if (_tag != Tags.Number) ThrowInvalidCase(nameof(Number));
            return _number_value;
        }
    }

    public bool TryGetBuf(out global::Buffer buffer)
    {
        if (_tag == Tags.Buf)
        {
            buffer = _buf_buffer;
            return true;
        }

        buffer = default!;
        return false;
    }

    public bool TryGetNumber(out int value)
    {
        if (_tag == Tags.Number)
        {
            value = _number_value;
            return true;
        }

        value = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<global::Buffer, TResult> buf, global::System.Func<int, TResult> number)
    {
        return _tag switch
        {
            Tags.Buf => buf(_buf_buffer),
            Tags.Number => number(_number_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public TResult Match<TState, TResult>(TState state, global::System.Func<TState, global::Buffer, TResult> buf, global::System.Func<TState, int, TResult> number)
    {
        return _tag switch
        {
            Tags.Buf => buf(state, _buf_buffer),
            Tags.Number => number(state, _number_value),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<global::Buffer> buf, global::System.Action<int> number)
    {
        switch (_tag)
        {
            case Tags.Buf: buf(_buf_buffer); break;
            case Tags.Number: number(_number_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public void Match<TState>(TState state, global::System.Action<TState, global::Buffer> buf, global::System.Action<TState, int> number)
    {
        switch (_tag)
        {
            case Tags.Buf: buf(state, _buf_buffer); break;
            case Tags.Number: number(state, _number_value); break;
            default: ThrowUnknownTag(); break;
        }
    }

    public static implicit operator Holder(global::Buffer value) => Buf(value);
    public static implicit operator Holder(int value) => Number(value);

    [global::System.Obsolete("Equals(object) is not supported on Holder because a ref struct cannot be boxed.", true)]
    public override bool Equals(object? obj) =>
        throw new global::System.NotSupportedException("Equals(object) is not supported on Holder because a ref struct cannot be boxed.");

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Buf => global::System.HashCode.Combine(_tag),
            Tags.Number => global::System.HashCode.Combine(_tag, _number_value),
            _ => _tag.GetHashCode()
        };
    }


    public override string ToString()
    {
        return _tag switch
        {
            Tags.Buf => $"Buf(<buffer>)",
            Tags.Number => $"Number({_number_value})",
            Tags.Default => "Default",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowUnknownTag() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
