//HintName: Payload.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Age          int          4B  (Both)
/// @ 4.. 8  Value        int          4B  (Number)
/// @ 8..16  Name         string       8B  (Both)
/// @ 8..16  Value        string       8B  (Text)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Text      8B
/// Number    4B
/// Both     12B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
public readonly partial struct Payload : global::System.IEquatable<Payload>
{
    private const byte TagText = 1;
    private const byte TagNumber = 2;
    private const byte TagBoth = 3;

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly byte _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly string _text_Value;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    private readonly int _number_Value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly string _both_Name;

    [global::System.Runtime.InteropServices.FieldOffset(4)]
    private readonly int _both_Age;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Payload() { }

    public static Payload Text(string value)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagText;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._text_Value) = value;
        return result;
    }

    public static Payload Number(int value)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagNumber;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._number_Value) = value;
        return result;
    }

    public static Payload Both(string name, int age)
    {
        var result = default(Payload);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = TagBoth;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._both_Name) = name;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._both_Age) = age;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public byte Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == 0;

    public bool IsText => _tag == TagText;
    public bool IsNumber => _tag == TagNumber;
    public bool IsBoth => _tag == TagBoth;

    public string TextValue
    {
        get
        {
            if (_tag != TagText) ThrowInvalidCase(nameof(Text));
            return _text_Value;
        }
    }
    public int NumberValue
    {
        get
        {
            if (_tag != TagNumber) ThrowInvalidCase(nameof(Number));
            return _number_Value;
        }
    }
    public string BothName
    {
        get
        {
            if (_tag != TagBoth) ThrowInvalidCase(nameof(Both));
            return _both_Name;
        }
    }
    public int BothAge
    {
        get
        {
            if (_tag != TagBoth) ThrowInvalidCase(nameof(Both));
            return _both_Age;
        }
    }

    public bool TryGetText(out string Value)
    {
        if (_tag == TagText)
        {
            Value = _text_Value;
            return true;
        }

        Value = default!;
        return false;
    }

    public bool TryGetNumber(out int Value)
    {
        if (_tag == TagNumber)
        {
            Value = _number_Value;
            return true;
        }

        Value = default!;
        return false;
    }

    public bool TryGetBoth(out string Name, out int Age)
    {
        if (_tag == TagBoth)
        {
            Name = _both_Name;
            Age = _both_Age;
            return true;
        }

        Name = default!;
        Age = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<string, TResult> text, global::System.Func<int, TResult> number, global::System.Func<string, int, TResult> both)
    {
        return _tag switch
        {
            TagText => text(_text_Value),
            TagNumber => number(_number_Value),
            TagBoth => both(_both_Name, _both_Age),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<string> text, global::System.Action<int> number, global::System.Action<string, int> both)
    {
        switch (_tag)
        {
            case TagText: text(_text_Value); break;
            case TagNumber: number(_number_Value); break;
            case TagBoth: both(_both_Name, _both_Age); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public static implicit operator Payload(string value) => Text(value);
    public static implicit operator Payload(int value) => Number(value);

    public bool Equals(Payload other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            TagText => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_text_Value, other._text_Value),
            TagNumber => global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_number_Value, other._number_Value),
            TagBoth => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_both_Name, other._both_Name) && global::System.Collections.Generic.EqualityComparer<int>.Default.Equals(_both_Age, other._both_Age),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Payload other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            TagText => global::System.HashCode.Combine(_tag, _text_Value),
            TagNumber => global::System.HashCode.Combine(_tag, _number_Value),
            TagBoth => global::System.HashCode.Combine(_tag, _both_Name, _both_Age),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Payload left, Payload right) => left.Equals(right);
    public static bool operator !=(Payload left, Payload right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            TagText => $"Text({_text_Value})",
            TagNumber => $"Number({_number_Value})",
            TagBoth => $"Both({_both_Name}, {_both_Age})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
