//HintName: Payload.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 3B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 4  ---          padding      3B
/// @ 4.. 8  Age          int          4B  (Both)
/// @ 4.. 8  Value        int          4B  (Number)
/// @ 8..16  Name         string       8B  (Both)
/// @ 8..16  Value        string       8B  (Text)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Text      8B
/// Number    4B
/// Both     12B
/// </code>
/// </remarks>
public partial record PayloadRecord { }
