//HintName: Message.Template.g.cs
// <auto-generated/>
#nullable enable

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  Items        int[]        8B  (Data)
/// @ 8..16  Ex           Exception    8B  (Error)
/// @ 8..16  Value        string       8B  (Text)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Text     8B
/// Data     8B
/// Error    8B
/// </code>
/// </remarks>
public partial record MessageRecord { }
