//HintName: Message.g.cs
// <auto-generated/>
#nullable enable
#pragma warning disable CS0282 // field ordering in partial struct
#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)
#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor

/// <summary>
/// Struct union with 3 variants.
/// </summary>
/// <remarks>
/// <para><b>16 bytes</b> · align 8 · 7B padding</para>
/// <code>
/// @ 0.. 1  _tag         byte         1B
/// @ 1.. 8  ---          padding      7B
/// @ 8..16  Items        int[]        8B  (Data)
/// @ 8..16  Ex           Exception    8B  (Error)
/// @ 8..16  Value        string       8B  (Text)
/// </code>
/// <para><b>Variants</b></para>
/// <code>
/// Text     8B
/// Data     8B
/// Error    8B
/// </code>
/// </remarks>
[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]
public readonly partial struct Message : global::System.IEquatable<Message>
{
    public enum Tags : byte
    {
        Default = 0,
        Text = 1,
        Data = 2,
        Error = 3,
    }

    [global::System.Runtime.InteropServices.FieldOffset(0)]
    private readonly Tags _tag;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly string _text_Value;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly int[] _data_Items;

    [global::System.Runtime.InteropServices.FieldOffset(8)]
    private readonly global::System.Exception _error_Ex;

    [global::System.Obsolete("Use factory methods instead.", true)]
    public Message() { }

    public static Message Text(string value)
    {
        var result = default(Message);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Text;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._text_Value) = value;
        return result;
    }

    public static Message Data(int[] items)
    {
        var result = default(Message);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Data;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._data_Items) = items;
        return result;
    }

    public static Message Error(global::System.Exception ex)
    {
        var result = default(Message);
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._tag) = Tags.Error;
        global::System.Runtime.CompilerServices.Unsafe.AsRef(in result._error_Ex) = ex;
        return result;
    }

    /// <summary>Gets the tag value identifying which variant is active.</summary>
    public Tags Tag => _tag;

    /// <summary>Returns true if this is a default-constructed instance with no active variant.</summary>
    public bool IsDefault => _tag == Tags.Default;

    public bool IsText => _tag == Tags.Text;
    public bool IsData => _tag == Tags.Data;
    public bool IsError => _tag == Tags.Error;

    public string TextValue
    {
        get
        {
            if (_tag != Tags.Text) ThrowInvalidCase(nameof(Text));
            return _text_Value;
        }
    }
    public int[] DataItems
    {
        get
        {
            if (_tag != Tags.Data) ThrowInvalidCase(nameof(Data));
            return _data_Items;
        }
    }
    public global::System.Exception ErrorEx
    {
        get
        {
            if (_tag != Tags.Error) ThrowInvalidCase(nameof(Error));
            return _error_Ex;
        }
    }

    public bool TryGetText(out string Value)
    {
        if (_tag == Tags.Text)
        {
            Value = _text_Value;
            return true;
        }

        Value = default!;
        return false;
    }

    public bool TryGetData(out int[] Items)
    {
        if (_tag == Tags.Data)
        {
            Items = _data_Items;
            return true;
        }

        Items = default!;
        return false;
    }

    public bool TryGetError(out global::System.Exception Ex)
    {
        if (_tag == Tags.Error)
        {
            Ex = _error_Ex;
            return true;
        }

        Ex = default!;
        return false;
    }

    public TResult Match<TResult>(global::System.Func<string, TResult> text, global::System.Func<int[], TResult> data, global::System.Func<global::System.Exception, TResult> error)
    {
        return _tag switch
        {
            Tags.Text => text(_text_Value),
            Tags.Data => data(_data_Items),
            Tags.Error => error(_error_Ex),
            _ => ThrowUnknownTag<TResult>()
        };
    }

    public void Match(global::System.Action<string> text, global::System.Action<int[]> data, global::System.Action<global::System.Exception> error)
    {
        switch (_tag)
        {
            case Tags.Text: text(_text_Value); break;
            case Tags.Data: data(_data_Items); break;
            case Tags.Error: error(_error_Ex); break;
            default: ThrowUnknownTag<int>(); break;
        }
    }

    public static implicit operator Message(string value) => Text(value);
    public static implicit operator Message(int[] value) => Data(value);
    public static implicit operator Message(global::System.Exception value) => Error(value);

    public bool Equals(Message other)
    {
        if (_tag != other._tag) return false;
        return _tag switch
        {
            Tags.Text => global::System.Collections.Generic.EqualityComparer<string>.Default.Equals(_text_Value, other._text_Value),
            Tags.Data => global::System.Collections.Generic.EqualityComparer<int[]>.Default.Equals(_data_Items, other._data_Items),
            Tags.Error => global::System.Collections.Generic.EqualityComparer<global::System.Exception>.Default.Equals(_error_Ex, other._error_Ex),
            _ => true
        };
    }

    public override bool Equals(object? obj) => obj is Message other && Equals(other);

    public override int GetHashCode()
    {
        return _tag switch
        {
            Tags.Text => global::System.HashCode.Combine(_tag, _text_Value),
            Tags.Data => global::System.HashCode.Combine(_tag, _data_Items),
            Tags.Error => global::System.HashCode.Combine(_tag, _error_Ex),
            _ => _tag.GetHashCode()
        };
    }

    public static bool operator ==(Message left, Message right) => left.Equals(right);
    public static bool operator !=(Message left, Message right) => !left.Equals(right);

    public override string ToString()
    {
        return _tag switch
        {
            Tags.Text => $"Text({_text_Value})",
            Tags.Data => $"Data({_data_Items})",
            Tags.Error => $"Error({_error_Ex})",
            _ => "<invalid>"
        };
    }

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static void ThrowInvalidCase(string caseName) =>
        throw new global::System.InvalidOperationException($"Cannot access {caseName} data when the union is not in the {caseName} state.");

    [global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]
    private static TResult ThrowUnknownTag<TResult>() =>
        throw new global::System.InvalidOperationException("Unknown union tag.");
}
