using StructUnion.Generator.Infrastructure;
using StructUnion.Generator.Models;

namespace StructUnion.Generator.Emitting;

static class UnionEmitter
{
    public static string Emit(UnionModel model)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS0282 // field ordering in partial struct");
        sb.AppendLine("#pragma warning disable CS0649 // field never assigned (Unsafe.AsRef)");
        sb.AppendLine("#pragma warning disable CS8618 // non-nullable field in [Obsolete] constructor");
        sb.AppendLine();

        // Namespace
        if (model.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.OpenBrace();
        }

        // Containing types
        foreach (var ct in model.ContainingTypes)
        {
            sb.AppendLine(ct);
            sb.OpenBrace();
        }

        // Layout documentation
        LayoutEmitter.Emit(sb, model);

        // Struct layout attribute
        if (model.Layout == LayoutStrategy.Explicit)
        {
            sb.AppendLine("[global::System.Runtime.InteropServices.StructLayout(global::System.Runtime.InteropServices.LayoutKind.Explicit)]");
        }

        // Struct declaration
        var typeParams = "";
        if (model.TypeParameters.Count > 0)
        {
            typeParams = $"<{string.Join(", ", model.TypeParameters.Select(tp => tp.Name))}>";
        }

        sb.AppendLine($"{model.Accessibility} readonly partial struct {model.Name}{typeParams} : global::System.IEquatable<{model.TypeNameWithParameters}>");

        // Type parameter constraints
        foreach (var tp in model.TypeParameters)
        {
            if (tp.Constraints.Count > 0)
            {
                sb.AppendLine($"    where {tp.Name} : {string.Join(", ", tp.Constraints)}");
            }
        }

        sb.OpenBrace();

        // Fields
        FieldEmitter.Emit(sb, model);
        sb.AppendLine();

        // Factory methods
        FactoryEmitter.Emit(sb, model);

        // Properties (Is-checks, accessors, TryGet)
        PropertyEmitter.Emit(sb, model);

        // Match methods
        MatchEmitter.Emit(sb, model);
        sb.AppendLine();

        // Implicit conversions
        EmitImplicitConversions(sb, model);

        // Equality
        EqualityEmitter.Emit(sb, model);
        sb.AppendLine();

        // ToString
        ToStringEmitter.Emit(sb, model);
        sb.AppendLine();

        // Error helpers
        sb.AppendLine("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        sb.AppendLine("private static void ThrowInvalidCase(string caseName) =>");
        using (sb.Indent())
        {
            sb.AppendLine("throw new global::System.InvalidOperationException($\"Cannot access {caseName} data when the union is not in the {caseName} state.\");");
        }

        sb.AppendLine();

        sb.AppendLine("[global::System.Runtime.CompilerServices.MethodImpl(global::System.Runtime.CompilerServices.MethodImplOptions.NoInlining)]");
        sb.AppendLine("private static TResult ThrowUnknownTag<TResult>() =>");
        using (sb.Indent())
        {
            sb.AppendLine("throw new global::System.InvalidOperationException(\"Unknown union tag.\");");
        }

        // Close struct
        sb.CloseBrace();

        // Close containing types
        for (var i = 0; i < model.ContainingTypes.Count; i++)
        {
            sb.CloseBrace();
        }

        // Close namespace
        if (model.Namespace.Length > 0)
        {
            sb.CloseBrace();
        }

        return sb.ToString();
    }

    public static string EmitTemplateDoc(UnionModel model)
    {
        var sb = new SourceBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (model.Namespace.Length > 0)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.OpenBrace();
        }

        foreach (var ct in model.ContainingTypes)
        {
            sb.AppendLine(ct);
            sb.OpenBrace();
        }

        LayoutEmitter.Emit(sb, model);
        sb.AppendLine($"{model.Accessibility} partial {model.TemplateTypeKeyword} {model.TemplateTypeName} {{ }}");

        for (var i = 0; i < model.ContainingTypes.Count; i++)
        {
            sb.CloseBrace();
        }

        if (model.Namespace.Length > 0)
        {
            sb.CloseBrace();
        }

        return sb.ToString();
    }

    static void EmitImplicitConversions(SourceBuilder sb, UnionModel model)
    {
        if (!model.EnableImplicitConversions)
        {
            return;
        }

        // Skip implicit conversions when common fields exist (factory methods require extra params)
        if (model.HasCommonFields)
        {
            return;
        }

        // Only generate for single-parameter variants with unique types
        var singleParamVariants = model.Variants
            .Where(v => v.Parameters.Count == 1)
            .ToList();

        var typeCounts = singleParamVariants
            .GroupBy(v => v.Parameters[0].TypeFullyQualified)
            .Where(g => g.Count() == 1)
            .Select(g => g.First())
            .ToList();

        foreach (var variant in typeCounts)
        {
            var param = variant.Parameters[0];
            sb.AppendLine($"public static implicit operator {model.TypeNameWithParameters}({param.TypeFullyQualified} value) => {variant.Name}(value);");
        }

        if (typeCounts.Count > 0)
        {
            sb.AppendLine();
        }
    }
}
